from __future__ import annotations
import hashlib, json
from datetime import datetime, timezone
from typing import Any
SCHEMA_BASELINE = "phase15.schema-baseline.v1"
def _now(): return datetime.now(timezone.utc).isoformat(timespec="seconds")
def _canon(v): return json.dumps(v, ensure_ascii=False, sort_keys=True, separators=(",",":"), default=str)
def _sha(v): return hashlib.sha256(_canon(v).encode()).hexdigest()
def ensure_phase15_schema_v1(db: Any) -> None:
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_schema_meta(schema_key TEXT PRIMARY KEY,value_json TEXT NOT NULL,updated_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_migration_runs(migration_id TEXT PRIMARY KEY,source_build TEXT NOT NULL,target_schema TEXT NOT NULL,source_path TEXT NOT NULL,source_sha256 TEXT NOT NULL,backup_path TEXT NOT NULL,backup_sha256 TEXT NOT NULL,report_path TEXT NOT NULL,status TEXT NOT NULL,started_at TEXT NOT NULL,completed_at TEXT,details_json TEXT NOT NULL)""")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_agent_tasks(task_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,agent_role TEXT NOT NULL,action_class TEXT NOT NULL,requested_gateway TEXT NOT NULL,approval_state TEXT NOT NULL,contract_version TEXT NOT NULL,task_json TEXT NOT NULL,record_hash TEXT NOT NULL,created_at TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_agent_tasks_case ON phase15_agent_tasks(case_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_agent_tasks_action ON phase15_agent_tasks(action_class,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_agent_results(result_id TEXT PRIMARY KEY,task_id TEXT NOT NULL,status TEXT NOT NULL,gateway_used TEXT NOT NULL,contract_version TEXT NOT NULL,result_json TEXT NOT NULL,record_hash TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(task_id) REFERENCES phase15_agent_tasks(task_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_agent_results_task ON phase15_agent_results(task_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_sources(source_id TEXT PRIMARY KEY,source_kind TEXT NOT NULL,locator TEXT NOT NULL,display_name TEXT NOT NULL,source_class TEXT NOT NULL,jurisdiction TEXT NOT NULL,allowed_use TEXT NOT NULL,review_status TEXT NOT NULL,risk_class TEXT NOT NULL,provenance_json TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,record_hash TEXT NOT NULL,UNIQUE(source_kind,locator))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_sources_review ON phase15_sources(source_kind,review_status,risk_class)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_source_review_events(event_id TEXT PRIMARY KEY,source_id TEXT NOT NULL,decision TEXT NOT NULL,rationale TEXT NOT NULL,reviewer TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(source_id) REFERENCES phase15_sources(source_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_source_reviews_source ON phase15_source_review_events(source_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_search_runs(search_run_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,task_id TEXT,search_kind TEXT NOT NULL,state TEXT NOT NULL,opsec_state TEXT NOT NULL,network_profile_ref TEXT,workspace_ref TEXT,policy_version TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,completed_at TEXT,summary_json TEXT NOT NULL,FOREIGN KEY(task_id) REFERENCES phase15_agent_tasks(task_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_search_runs_case ON phase15_search_runs(case_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_media_assets(media_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,evidence_id TEXT,media_kind TEXT NOT NULL,object_ref TEXT NOT NULL,sha256 TEXT NOT NULL,metadata_json TEXT NOT NULL,review_status TEXT NOT NULL,created_at TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_media_case ON phase15_media_assets(case_id,created_at)")
    db.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_phase15_media_hash ON phase15_media_assets(sha256,object_ref)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_object_links(link_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,from_type TEXT NOT NULL,from_id TEXT NOT NULL,relation TEXT NOT NULL,to_type TEXT NOT NULL,to_id TEXT NOT NULL,provenance_json TEXT NOT NULL,created_at TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_links_from ON phase15_object_links(case_id,from_type,from_id)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_links_to ON phase15_object_links(case_id,to_type,to_id)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_security_events(security_event_id TEXT PRIMARY KEY,case_id TEXT,search_run_id TEXT,event_type TEXT NOT NULL,disposition TEXT NOT NULL,severity TEXT NOT NULL,policy_version TEXT NOT NULL,evidence_json TEXT NOT NULL,created_at TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_security_run ON phase15_security_events(search_run_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_network_profiles(profile_id TEXT PRIMARY KEY,profile_kind TEXT NOT NULL,display_name TEXT NOT NULL,allowed_schemes_json TEXT NOT NULL,dns_mode TEXT NOT NULL,webrtc_mode TEXT NOT NULL,system_mutation_allowed INTEGER NOT NULL DEFAULT 0,runtime_execution_enabled INTEGER NOT NULL DEFAULT 0,review_status TEXT NOT NULL,config_ref TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_network_profiles_kind ON phase15_network_profiles(profile_kind,review_status)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_search_capsules(search_run_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,task_id TEXT,search_kind TEXT NOT NULL,capsule_state TEXT NOT NULL,network_profile_ref TEXT NOT NULL,workspace_ref TEXT NOT NULL,key_fingerprint TEXT NOT NULL,egress_allowlist_json TEXT NOT NULL,resource_limits_json TEXT NOT NULL,isolation_json TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,expires_at TEXT NOT NULL,closed_at TEXT,FOREIGN KEY(search_run_id) REFERENCES phase15_search_runs(search_run_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_capsules_case ON phase15_search_capsules(case_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_opsec_decisions(decision_id TEXT PRIMARY KEY,search_run_id TEXT NOT NULL,request_seq INTEGER NOT NULL,target_scheme TEXT NOT NULL,target_host TEXT NOT NULL,source_id TEXT,disposition TEXT NOT NULL,reason_codes_json TEXT NOT NULL,checks_json TEXT NOT NULL,policy_version TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(search_run_id) REFERENCES phase15_search_capsules(search_run_id),UNIQUE(search_run_id,request_seq))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_opsec_decisions_run ON phase15_opsec_decisions(search_run_id,request_seq)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_capsule_logs(log_id TEXT PRIMARY KEY,search_run_id TEXT NOT NULL,event_type TEXT NOT NULL,severity TEXT NOT NULL,encrypted_ref TEXT NOT NULL,digest_sha256 TEXT NOT NULL,redaction_summary_json TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(search_run_id) REFERENCES phase15_search_capsules(search_run_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_capsule_logs_run ON phase15_capsule_logs(search_run_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_opsec_assessments(assessment_id TEXT PRIMARY KEY,search_run_id TEXT NOT NULL,case_id TEXT NOT NULL,stage TEXT NOT NULL,disposition TEXT NOT NULL,severity TEXT NOT NULL,risk_score INTEGER NOT NULL,signals_json TEXT NOT NULL,evidence_json TEXT NOT NULL,policy_version TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(search_run_id) REFERENCES phase15_search_capsules(search_run_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_opsec_assessments_run ON phase15_opsec_assessments(search_run_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_opsec_assessments_severity ON phase15_opsec_assessments(severity,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_opsec_training_cases(training_id TEXT PRIMARY KEY,case_key TEXT NOT NULL,category TEXT NOT NULL,source_ref TEXT NOT NULL,license_or_terms TEXT NOT NULL,payload_hash TEXT NOT NULL,expected_label TEXT NOT NULL,split TEXT NOT NULL,review_state TEXT NOT NULL,reviewer_id TEXT,reviewed_at TEXT,label_reason TEXT,created_by TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_opsec_training_review ON phase15_opsec_training_cases(review_state,category,split)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_dossier_releases(release_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,dossier_ref TEXT NOT NULL,release_state TEXT NOT NULL,reviewer TEXT NOT NULL,manifest_json TEXT NOT NULL,created_at TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_dossier_case ON phase15_dossier_releases(case_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_data_backends(backend_id TEXT PRIMARY KEY,backend_kind TEXT NOT NULL,role TEXT NOT NULL,status TEXT NOT NULL,config_json TEXT NOT NULL,live_validated INTEGER NOT NULL DEFAULT 0,last_checked_at TEXT,created_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_data_backends_kind ON phase15_data_backends(backend_kind,status)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_backend_contract_runs(run_id TEXT PRIMARY KEY,backend_id TEXT NOT NULL,backend_kind TEXT NOT NULL,mode TEXT NOT NULL,status TEXT NOT NULL,details_json TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_backend_contract_backend ON phase15_backend_contract_runs(backend_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_objects(object_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,search_run_id TEXT,source_id TEXT,backend_id TEXT NOT NULL,object_key TEXT NOT NULL,sha256 TEXT NOT NULL,size_bytes INTEGER NOT NULL,media_type TEXT NOT NULL,security_state TEXT NOT NULL,provenance_json TEXT NOT NULL,created_by TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_objects_case ON phase15_objects(case_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_objects_run ON phase15_objects(search_run_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_objects_sha ON phase15_objects(sha256,backend_id)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_object_events(event_id TEXT PRIMARY KEY,object_id TEXT NOT NULL,event_type TEXT NOT NULL,decision TEXT NOT NULL,actor TEXT NOT NULL,details_json TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(object_id) REFERENCES phase15_objects(object_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_object_events_object ON phase15_object_events(object_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_search_backends(backend_id TEXT PRIMARY KEY,backend_kind TEXT NOT NULL,status TEXT NOT NULL,config_json TEXT NOT NULL,live_validated INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_search_backends_kind ON phase15_search_backends(backend_kind,status)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_search_documents(doc_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,object_id TEXT NOT NULL DEFAULT '',source_id TEXT NOT NULL DEFAULT '',title TEXT NOT NULL,body_sha256 TEXT NOT NULL,security_state TEXT NOT NULL,provenance_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_search_documents_case ON phase15_search_documents(case_id,updated_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_search_documents_object ON phase15_search_documents(object_id)")
    db.execute("CREATE VIRTUAL TABLE IF NOT EXISTS phase15_search_fts USING fts5(doc_id UNINDEXED,case_id UNINDEXED,title,body,tokenize='unicode61')")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_jobs(job_id TEXT PRIMARY KEY,idempotency_key TEXT NOT NULL UNIQUE,job_type TEXT NOT NULL,case_id TEXT NOT NULL DEFAULT '',search_run_id TEXT NOT NULL DEFAULT '',status TEXT NOT NULL,priority INTEGER NOT NULL,attempts INTEGER NOT NULL,max_attempts INTEGER NOT NULL,available_at TEXT NOT NULL,lease_owner TEXT NOT NULL DEFAULT '',lease_expires_at TEXT NOT NULL DEFAULT '',payload_json TEXT NOT NULL,resource_budget_json TEXT NOT NULL,rate_budget_json TEXT NOT NULL,checkpoint_json TEXT NOT NULL,result_json TEXT NOT NULL,error_text TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_jobs_ready ON phase15_jobs(status,available_at,priority,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_jobs_case ON phase15_jobs(case_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_jobs_run ON phase15_jobs(search_run_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_job_events(event_id TEXT PRIMARY KEY,job_id TEXT NOT NULL,event_type TEXT NOT NULL,actor TEXT NOT NULL,details_json TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(job_id) REFERENCES phase15_jobs(job_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_job_events_job ON phase15_job_events(job_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_crawler_policies(source_id TEXT PRIMARY KEY,seed_urls_json TEXT NOT NULL,allowed_hosts_json TEXT NOT NULL,terms_ref TEXT NOT NULL,robots_mode TEXT NOT NULL,auth_type TEXT NOT NULL,max_depth INTEGER NOT NULL,max_pages INTEGER NOT NULL,requests_per_minute INTEGER NOT NULL,max_response_bytes INTEGER NOT NULL,parser_version TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,source_health TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(source_id) REFERENCES phase15_sources(source_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_crawler_policy_enabled ON phase15_crawler_policies(enabled,source_health)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_crawl_runs(crawl_run_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,source_id TEXT NOT NULL,search_run_id TEXT NOT NULL,status TEXT NOT NULL,pages_fetched INTEGER NOT NULL,pages_stored INTEGER NOT NULL,bytes_fetched INTEGER NOT NULL,started_at TEXT,completed_at TEXT,created_at TEXT NOT NULL,summary_json TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(source_id) REFERENCES phase15_sources(source_id),FOREIGN KEY(search_run_id) REFERENCES phase15_search_runs(search_run_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_crawl_runs_case ON phase15_crawl_runs(case_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_crawl_runs_source ON phase15_crawl_runs(source_id,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_crawl_fetches(fetch_id TEXT PRIMARY KEY,crawl_run_id TEXT NOT NULL,url TEXT NOT NULL,depth INTEGER NOT NULL,status_code INTEGER NOT NULL,content_type TEXT NOT NULL,content_sha256 TEXT NOT NULL,size_bytes INTEGER NOT NULL,elapsed_ms INTEGER NOT NULL,disposition TEXT NOT NULL,reason TEXT NOT NULL,object_id TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(crawl_run_id) REFERENCES phase15_crawl_runs(crawl_run_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_crawl_fetches_run ON phase15_crawl_fetches(crawl_run_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_crawl_fetches_hash ON phase15_crawl_fetches(content_sha256)")
    # Build 351 extends the consolidated fetch ledger in place; no per-build table.
    # Columns are additive and preserve Build-349/350 rows with empty defaults.
    for column, definition in (
        ("etag", "TEXT NOT NULL DEFAULT ''"),
        ("last_modified", "TEXT NOT NULL DEFAULT ''"),
        ("canonical_url", "TEXT NOT NULL DEFAULT ''"),
        ("change_state", "TEXT NOT NULL DEFAULT ''"),
        ("previous_fetch_id", "TEXT NOT NULL DEFAULT ''"),
    ):
        db._ensure_column("phase15_crawl_fetches", column, definition)
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_crawl_fetches_url_time ON phase15_crawl_fetches(url,created_at)")
    # Build 352 extends crawler policy in place: persistent frontier stays in phase15_jobs.checkpoint_json.
    for column, definition in (
        ("sitemap_urls_json", "TEXT NOT NULL DEFAULT '[]'"),
        ("archive_seed_urls_json", "TEXT NOT NULL DEFAULT '[]'"),
        ("frontier_policy_json", "TEXT NOT NULL DEFAULT '{}'"),
    ):
        db._ensure_column("phase15_crawler_policies", column, definition)
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_connector_manifests(connector_key TEXT PRIMARY KEY,display_name TEXT NOT NULL,provider TEXT NOT NULL,source_class TEXT NOT NULL,jurisdiction TEXT NOT NULL,base_host TEXT NOT NULL,auth_type TEXT NOT NULL,parser_version TEXT NOT NULL,terms_ref TEXT NOT NULL,official_ref TEXT NOT NULL,status TEXT NOT NULL,config_json TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,record_hash TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_connector_manifest_status ON phase15_connector_manifests(status,provider)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_connector_source_links(source_id TEXT PRIMARY KEY,connector_key TEXT NOT NULL,identifier TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(source_id) REFERENCES phase15_sources(source_id),FOREIGN KEY(connector_key) REFERENCES phase15_connector_manifests(connector_key))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_connector_source_key ON phase15_connector_source_links(connector_key,identifier)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_parse_runs(parse_run_id TEXT PRIMARY KEY,object_id TEXT NOT NULL,source_id TEXT NOT NULL DEFAULT '',parser_version TEXT NOT NULL,media_type TEXT NOT NULL,status TEXT NOT NULL,record_count INTEGER NOT NULL,normalized_json TEXT NOT NULL,warnings_json TEXT NOT NULL,error_text TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(object_id) REFERENCES phase15_objects(object_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_parse_runs_object ON phase15_parse_runs(object_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_parse_runs_source ON phase15_parse_runs(source_id,status,created_at)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_source_health_events(health_id TEXT PRIMARY KEY,source_id TEXT NOT NULL,status TEXT NOT NULL,details_json TEXT NOT NULL,created_at TEXT NOT NULL,record_hash TEXT NOT NULL,FOREIGN KEY(source_id) REFERENCES phase15_sources(source_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_source_health_source ON phase15_source_health_events(source_id,created_at)")
    # Build 359 canonical team identity/RBAC layer. This deliberately replaces any
    # temptation to reactivate the large legacy Build-146 governance schema.
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_team_users(user_id TEXT PRIMARY KEY,username TEXT NOT NULL COLLATE NOCASE UNIQUE,display_name TEXT NOT NULL,password_hash TEXT NOT NULL,global_role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,must_change_password INTEGER NOT NULL DEFAULT 0,session_generation INTEGER NOT NULL DEFAULT 0,failed_attempts INTEGER NOT NULL DEFAULT 0,lock_until_epoch INTEGER NOT NULL DEFAULT 0,created_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_team_users_role ON phase15_team_users(global_role,active)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_team_sessions(session_id TEXT PRIMARY KEY,token_hash TEXT NOT NULL UNIQUE,csrf_hash TEXT NOT NULL,user_id TEXT NOT NULL,client_fingerprint_hash TEXT NOT NULL,session_generation INTEGER NOT NULL,created_epoch INTEGER NOT NULL,last_seen_epoch INTEGER NOT NULL,idle_expires_epoch INTEGER NOT NULL,absolute_expires_epoch INTEGER NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,revoked_reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES phase15_team_users(user_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_team_sessions_user ON phase15_team_sessions(user_id,revoked,absolute_expires_epoch)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_team_sessions_expiry ON phase15_team_sessions(revoked,idle_expires_epoch,absolute_expires_epoch)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_case_memberships(membership_id TEXT PRIMARY KEY,case_id TEXT NOT NULL,user_id TEXT NOT NULL,case_role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1,granted_by TEXT NOT NULL,granted_at TEXT NOT NULL,revoked_by TEXT,revoked_at TEXT,notes TEXT NOT NULL DEFAULT '',UNIQUE(case_id,user_id,case_role),FOREIGN KEY(user_id) REFERENCES phase15_team_users(user_id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_memberships_case ON phase15_case_memberships(case_id,active,case_role)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_memberships_user ON phase15_case_memberships(user_id,active,case_id)")
    db.execute("""CREATE TABLE IF NOT EXISTS phase15_access_events(sequence INTEGER PRIMARY KEY AUTOINCREMENT,event_id TEXT NOT NULL UNIQUE,event_type TEXT NOT NULL,user_id TEXT,username_hash TEXT NOT NULL,session_id TEXT NOT NULL,case_id TEXT NOT NULL,capability TEXT NOT NULL,allowed INTEGER NOT NULL,reason TEXT NOT NULL,object_type TEXT NOT NULL,object_id TEXT NOT NULL,details_json TEXT NOT NULL,previous_hash TEXT NOT NULL,event_hash TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL)""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_access_case ON phase15_access_events(case_id,sequence)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_phase15_access_user ON phase15_access_events(user_id,sequence)")
    db.execute("CREATE TRIGGER IF NOT EXISTS trg_phase15_access_events_no_update BEFORE UPDATE ON phase15_access_events BEGIN SELECT RAISE(ABORT,'phase15_access_events immutable'); END")
    db.execute("CREATE TRIGGER IF NOT EXISTS trg_phase15_access_events_no_delete BEFORE DELETE ON phase15_access_events BEGIN SELECT RAISE(ABORT,'phase15_access_events immutable'); END")
    for table in ("phase15_agent_tasks","phase15_agent_results","phase15_objects"):
        db.execute(f"CREATE TRIGGER IF NOT EXISTS trg_{table}_no_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT,'{table} immutable'); END")
        db.execute(f"CREATE TRIGGER IF NOT EXISTS trg_{table}_no_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT,'{table} immutable'); END")
    policy={"schema":SCHEMA_BASELINE,"per_build_tables_forbidden":True,"legacy_schema_auto_bootstrap":False,"search_capsule":{"required_for_external_requests":True,"per_search_workspace":True,"per_search_key":True,"separate_http_browser_state":True,"egress_allowlist_required":True,"request_preflight_required":True,"system_mutation_allowed":False,"runtime_network_execution_enabled":False},"data_platform":{"sqlite_portable":True,"postgresql_opt_in":True,"postgresql_auto_connect":False,"object_store_local_cas":True,"s3_opt_in":True,"external_backend_credentials_persisted":False,"search_backend_local_fts5":True,"search_backend_team_opt_in":True,"persistent_jobs":True,"background_workers_auto_started":False,"governed_crawler_v1":True,"crawler_auto_started":False,"connector_parser_sdk_v1":True,"source_health_v1":True,"crawler_frontier_resume_v1":True,"sitemap_discovery_v1":True,"investigation_supervisor_v356":True,"cross_modal_fusion_v356":True,"ai_dossier_v356":True,"speech_output_local_v356":True,"voice_gateway_v358":True,"voice_push_to_talk_v358":True,"voice_confirmation_gate_v358":True,"team_identity_rbac_v359":True,"four_eyes_export_v359":True,"crawler_ops_recovery_v359":True},"darknet":{"public_or_authorized_read_only":True,"network_execution_enabled":False,"human_source_review_required":True,"crawler_transport_requires_explicit_gateway":True,"opsec_preflight_required":True,"opsec_intelligence_v2_required":True,"approved_tor_profile_required":True,"credentials":False,"forms":False,"uploads":False,"payments":False,"access_control_bypass":False,"stolen_or_private_dataset_acquisition":False}}
    now=_now(); db.execute("INSERT OR REPLACE INTO phase15_schema_meta(schema_key,value_json,updated_at,record_hash) VALUES(?,?,?,?)",("baseline_policy",_canon(policy),now,_sha(policy)))
