from __future__ import annotations
import hashlib,json,secrets,tempfile
from pathlib import Path
from eagleeye_pro.core.app_context import AppContext
from eagleeye_pro.phase17.evidence_review390 import CONFIRM_ASSESS,CONFIRM_FINALIZE
from eagleeye_pro.phase17.investigation_synthesis391 import CONFIRM_CLAIM_REVIEW,CONFIRM_HYPOTHESIS_REVIEW,CONFIRM_KERNEL_ADMISSION,CONFIRM_SNAPSHOT
PW='Acceptance391-Orbit!'
def cand(c,cid,source,norm):
 raw=json.dumps({'s':source,'n':norm},sort_keys=True).encode(); oid='a391_'+secrets.token_hex(7); sha=hashlib.sha256(raw).hexdigest(); now='2026-09-13T15:30:00+00:00'; c.db.execute("INSERT INTO phase15_objects(object_id,case_id,search_run_id,source_id,backend_id,object_key,sha256,size_bytes,media_type,security_state,provenance_json,created_by,created_at,record_hash) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",(oid,cid,'','canon_'+source,'local',oid,sha,len(raw),'application/json','review_pending','{}','accept391',now,hashlib.sha256(raw+b'r').hexdigest())); obj={'object_id':oid,'sha256':sha,'media_type':'application/json','security_state':'review_pending'}; rr={'wave_number':1,'phase17_source_id':source,'canonical_source_id':'canon_'+source,'dispatch_id':'d'+oid,'job_id':'j'+oid,'crawl_run_id':'c'+oid,'search_run_id':'s'+oid}; out,_=c.result_intake_389._insert_candidate(case_id=cid,session_id='accept391',result_row=rr,obj=obj,parse_run_id='p'+oid,record_index=0,candidate_type='normalized_record',normalized=norm,provenance={}); return out
def finalized(c,a,cid):
 g=cand(c,cid,'gleif.lei',{'name':'Example GmbH','status':'ACTIVE'}); s=cand(c,cid,'sec.edgar',{'name':'Example GmbH','status':'INACTIVE'}); r=c.build390.create_corroboration_review(case_id=cid,proposition='Example GmbH is active',candidate_stances={g['candidate_id']:'supports',s['candidate_id']:'contradicts'},identity=a); c.build390.assess_corroboration_review(case_id=cid,review_id=r['review_id'],identity=a,confirmation=CONFIRM_ASSESS); c.build390.finalize_corroboration_review(case_id=cid,review_id=r['review_id'],identity=a,disposition='contested_requires_analysis',confirmation=CONFIRM_FINALIZE); return r['review_id']
def main():
 root=Path(__file__).resolve().parent; checks={}
 with tempfile.TemporaryDirectory() as td:
  with AppContext(base_dir=td,actor='accept391') as c:
   a=c.team_identity_359.create_initial_admin(username='accept391',display_name='Lead Reviewer 391',password=PW); a={**a,'session_id':'accept391'}; cid=c.build380.team_create_case(identity=a,title='accept391',client='internal',purpose='qualification',legal_basis='public_data')['case_id']; _=c.execution_authority_386; rid=finalized(c,a,cid)
   before=(int((c.db.one('SELECT COUNT(*) n FROM phase15_jobs') or {})['n']),int((c.db.one('SELECT COUNT(*) n FROM execution_grant_386') or {})['n']),int((c.db.one('SELECT COUNT(*) n FROM evidence_candidate_promotion_389') or {})['n']),int((c.db.one('SELECT COUNT(*) n FROM hypotheses_112') or {})['n']))
   cl=c.build391.synthesize_corroboration_review(case_id=cid,review_id=rid,identity=a); cl=c.build391.review_synthesis_claim(case_id=cid,claim_id=cl['claim_id'],identity=a,disposition='contested_requires_analysis',rationale='Contradiction preserved for hypothesis testing and further evidence.',confirmation=CONFIRM_CLAIM_REVIEW)
   h=c.build391.propose_hypothesis(case_id=cid,title='Timing explanation',statement='The contradictory status observations may reflect different effective dates.',test_plan='Compare filing dates, effective dates, and registry history.',claim_relations={cl['claim_id']:'test_target'},identity=a); h=c.build391.review_synthesis_hypothesis(case_id=cid,hypothesis_id=h['hypothesis_id'],identity=a,disposition='retain_for_testing',rationale='The explanation is testable and remains explicitly hypothetical.',confirmation=CONFIRM_HYPOTHESIS_REVIEW); kb=c.build391.admit_hypothesis_to_kernel(case_id=cid,hypothesis_id=h['hypothesis_id'],identity=a,confirmation=CONFIRM_KERNEL_ADMISSION); snap=c.build391.create_synthesis_snapshot(case_id=cid,identity=a,confirmation=CONFIRM_SNAPSHOT); feed=c.build391.ai_investigation_synthesis_feed(case_id=cid,identity=a)
   after=(int((c.db.one('SELECT COUNT(*) n FROM phase15_jobs') or {})['n']),int((c.db.one('SELECT COUNT(*) n FROM execution_grant_386') or {})['n']),int((c.db.one('SELECT COUNT(*) n FROM evidence_candidate_promotion_389') or {})['n']),int((c.db.one('SELECT COUNT(*) n FROM hypotheses_112') or {})['n']))
   checks={'version_coherent':c.build391.version_status()['coherent'],'schema_integrity':c.build391.schema_metrics()['within_phase17_gate'],'predecessor_390':c.build391.historical_build390_receipt()['valid'],'candidate_claim_not_fact':cl['epistemic_status']=='candidate_claim_not_fact' and cl['truth_determined'] is False,'counterevidence_preserved':len(cl['counterevidence_candidate_ids'])==1,'claim_reviewed':cl['status']=='reviewed_candidate','hypothesis_not_fact':h['epistemic_status']=='hypothesis_not_fact' and h['probability_assigned'] is False,'legacy_probability_unused':h['legacy_kernel_confidence_used'] is False and before[3]==after[3],'kernel_notebook_bridge':bool(kb.get('kernel_entry_id')),'snapshot_created':bool(snap.get('snapshot_hash')),'feed_layers':bool(feed['claims']) and bool(feed['hypotheses']) and bool(feed['counterevidence']),'no_jobs_grants_promotions':before[:3]==after[:3],'claim_hash_valid':c.build391.verify_synthesis_claim(case_id=cid,claim_id=cl['claim_id'])['valid'],'hypothesis_hash_valid':c.build391.verify_synthesis_hypothesis(case_id=cid,hypothesis_id=h['hypothesis_id'])['valid'],'no_truth_probability':feed['truth_determined'] is False and feed['probability_assigned'] is False,'no_direct_fetch':c.investigation_synthesis_391.status()['direct_network_fetch'] is False}
   fp=c.build391.code_fingerprint()
 result='pass' if all(checks.values()) else 'fail'; payload={'build':'391.0','result':result,'passed':sum(checks.values()),'total':len(checks),'checks':checks,'code_fingerprint':fp}; (root/'ACCEPTANCE_RESULTS_BUILD_391_0.json').write_text(json.dumps(payload,indent=2,sort_keys=True)); print(json.dumps(payload,indent=2)); raise SystemExit(0 if result=='pass' else 1)
if __name__=='__main__': main()
