from eagleeye.application.build193.service import Build193SourceNativeAIInvestigatorService
SourceNativeAIInvestigatorService = Build193SourceNativeAIInvestigatorService
__all__ = ["SourceNativeAIInvestigatorService", "Build193SourceNativeAIInvestigatorService"]
