from __future__ import annotations
from typing import Any, Callable


def render_final145(ctx: Any, case_id: str, csrf: str, *, esc: Callable[[Any], str], table: Callable[..., str]) -> str:
    rc = ctx.build144.dashboard(case_id)
    data = ctx.build145.dashboard(case_id)
    latest = rc.get("latest_audit") or {}
    baseline_options = "".join(f'<option value="{esc(row["baseline145_id"])}">{esc(row["baseline_label"])} · {esc(row["status"])}</option>' for row in data.get("baselines", []))
    seal_options = "".join(f'<option value="{esc(row["seal145_id"])}">{esc(row["seal145_id"])} · {esc(row["last_verification_status"] or row["status"])}</option>' for row in data.get("seals", []))
    return f'''
<div class="notice"><b>Build 145 · Phase-4 Final Baseline:</b> Audit, verifiziertes Backup, sichere Wartung, Vier-Augen-Prüfung und unveränderliches Release-Seal schließen Phase 4 kontrolliert ab. Das Seal ist eine lokale Integritätsbaseline, keine externe Zertifizierung.</div>
<div class="metrics"><div class="metric"><div class="label">Phase-4-Status</div><div class="value">{esc(data["phase4_status"])}</div></div><div class="metric"><div class="label">Letzter RC-Score</div><div class="value">{esc(latest.get("score", "–"))}</div></div><div class="metric"><div class="label">Versiegelte Baselines</div><div class="value">{esc(data["metrics"]["sealed_baselines"])}</div></div><div class="metric"><div class="label">Verifizierte Seals</div><div class="value">{esc(data["metrics"]["verified_seals"])}</div></div></div>
<div class="two-col"><div class="panel"><h2>1. Vollständiges RC-Audit</h2><form method="post" action="/final144/audit"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="include_optional" value="1"><p><button>Alle lokalen Tests ausführen</button></p></form><p class="footer">Datenbank, Code, Dateien, Eventketten, Reports, Fotos, OPSEC und Performance.</p></div>
<div class="panel"><h2>2. Verifiziertes Backup</h2><form method="post" action="/final144/backup"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Freigabephrase</label><input name="confirmation" value="VERIFIZIERTES PHASE-4-BACKUP ERZEUGEN" required></div><p><button>Backup und Restore-Test</button></p></form></div></div>
<div class="two-col"><div class="panel"><h2>3. Sichere Wartung</h2><p>Dry Run zeigt Dubletten, abgelaufene Derivate, WAL- und Seitenzustand. Anwendung optimiert SQLite und entfernt nur abgelaufene Recherchederivate.</p><form method="post" action="/final145/maintenance"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><label><input type="checkbox" name="apply" value="1"> Wartung anwenden</label><div class="field"><label>Freigabephrase bei Anwendung</label><input name="confirmation" placeholder="SICHERE PHASE-4-WARTUNG ANWENDEN"></div><p><button>Wartungsprüfung starten</button></p></form></div>
<div class="panel"><h2>4. Gesundheitszustand</h2><form method="post" action="/final145/health"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><p><button>Finalen Zustand prüfen</button></p></form><p class="footer">Erfordert freigabefähiges Audit, verifiziertes Backup, keine hohen offenen Risiken und keine aktive Research-Sitzung.</p></div></div>
<div class="panel"><h2>5. Baseline erzeugen</h2><form method="post" action="/final145/baseline"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="form-grid"><div class="field"><label>Baseline-Bezeichnung</label><input name="baseline_label" value="Phase 4 Final Baseline"></div><div class="field"><label>Freigabephrase</label><input name="confirmation" value="PHASE 4 BASELINE ERZEUGEN" required></div></div><p><button>Baseline zur unabhängigen Prüfung erstellen</button></p></form></div>
<div class="two-col"><div class="panel"><h2>6. Vier-Augen-Review</h2><form method="post" action="/final145/review"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Baseline</label><select name="baseline_id" required>{baseline_options}</select></div><div class="field"><label>Entscheidung</label><select name="decision"><option value="approved">Genehmigt</option><option value="revision_required">Überarbeitung</option><option value="rejected">Abgelehnt</option></select></div><div class="field"><label>Begründung</label><textarea name="reason" required></textarea></div><div class="field"><label>Freigabephrase</label><input name="confirmation" value="PHASE-4-BASELINE PRÜFEN" required></div><p><button>Review dokumentieren</button></p></form></div>
<div class="panel"><h2>7. Phase 4 versiegeln</h2><form method="post" action="/final145/seal"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Genehmigte Baseline</label><select name="baseline_id" required>{baseline_options}</select></div><div class="field"><label>Freigabephrase</label><input name="confirmation" value="PHASE 4 ABSCHLUSS FREIGEBEN" required></div><p><button>Unveränderliches Release-Seal erzeugen</button></p></form></div></div>
<div class="panel"><h2>Seal verifizieren</h2><form method="post" action="/final145/verify"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Seal</label><select name="seal_id" required>{seal_options}</select></div><p><button>SHA-256- und Manifestprüfung</button></p></form></div>
<div class="panel"><h2>Build-144-Audits</h2>{table(rc.get("audits", []), [("completed_at","Zeit"),("status","Status"),("score","Score"),("blocker_count","Blocker"),("warning_count","Warnungen")])}</div>
<div class="two-col"><div class="panel"><h2>Wartungsläufe</h2>{table(data.get("maintenance", []), [("created_at","Zeit"),("dry_run","Dry Run"),("status","Status"),("created_by","Akteur")])}</div><div class="panel"><h2>Health Snapshots</h2>{table(data.get("snapshots", []), [("created_at","Zeit"),("status","Status"),("score","Score"),("audit144_id","Audit"),("backup144_id","Backup")])}</div></div>
<div class="panel"><h2>Baselines</h2>{table(data.get("baselines", []), [("baseline_label","Baseline"),("status","Status"),("requested_by","Antrag"),("reviewed_by","Review"),("sealed","Versiegelt"),("updated_at","Aktualisiert")])}</div>
<div class="panel"><h2>Release-Seals</h2>{table(data.get("seals", []), [("seal145_id","Seal"),("status","Status"),("verification_count","Prüfungen"),("last_verification_status","Letzte Prüfung"),("created_at","Erstellt")])}</div>
<p class="footer">Automatische Identitätsaussagen: 0 · Biometrische Templates: 0 · Automatische Bilduploads: 0 · Autonome Außenaktionen: 0.</p>
'''
