from __future__ import annotations

from typing import Any, Callable


def _options(rows: list[dict[str, Any]], value: str, label: str, esc: Callable[[Any], str], *, empty: str = "") -> str:
    result = [f'<option value="">{esc(empty)}</option>'] if empty else []
    result.extend(f'<option value="{esc(row[value])}">{esc(row[label])}</option>' for row in rows)
    return "".join(result)


def render_identity139(ctx: Any, case_id: str, csrf: str, *, esc: Callable[[Any], str]) -> str:
    data = ctx.build139.dashboard(case_id)
    identity = data["identity"]
    assistant = data["assistant"]
    targets = ctx.targets.list_targets(case_id)
    target_options = _options(targets, "target_id", "name", esc, empty="Zielperson auswählen")
    candidate_rows: list[str] = []
    for row in identity["candidates"]:
        attrs = row.get("attributes") or {}
        summary = ", ".join(f"{key}: {' / '.join(str(v) for v in values[:3])}" for key, values in attrs.items() if values) or "Keine Kandidatenattribute"
        score = row.get("overall_score")
        score_label = "noch nicht verglichen" if score is None else f"{float(score):.2f} · {row.get('result_band') or ''}"
        candidate_rows.append(f'''
<article class="intake-card"><div class="intake-head"><div><h3>{esc(row['label'])}</h3><p>{esc(summary)}</p></div><div><span class="badge candidate">{esc(row['review_status'])}</span></div></div>
<p><b>Erklärbarer Identitätsscore:</b> {esc(score_label)} · Konflikt: {esc(row.get('conflict_score') if row.get('conflict_score') is not None else '—')} · Gesichtsmerkmale verwendet: <b>nein</b></p>
<div class="inline"><form method="post" action="/identity139/compare"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="candidate_id" value="{esc(row['candidate_id'])}"><button class="small">Nichtbiometrisch vergleichen</button></form></div>
<form method="post" action="/identity139/decision"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="candidate_id" value="{esc(row['candidate_id'])}"><div class="form-grid"><div class="field"><label>Manuelle Entscheidung</label><select name="decision"><option value="requires_more_evidence">Weitere Belege nötig</option><option value="same_person_hypothesis">Gleiche-Person-Hypothese</option><option value="not_same_person">Nicht dieselbe Person</option><option value="confirmed_by_investigator">Durch Ermittler bestätigt</option></select></div><div class="field"><label>Bestätigungsphrase nur für Bestätigung</label><input name="confirmation" placeholder="IDENTITÄT MANUELL BESTÄTIGEN"></div></div><div class="field"><label>Begründung</label><textarea name="rationale" rows="3" required></textarea></div><button class="small ghost">Manuelle Bewertung speichern</button></form></article>''')
    briefs = assistant.get("briefs", [])
    opsec = assistant.get("opsec", [])
    brief_table = "".join(f"<tr><td>{esc(r['created_at'])}</td><td>{esc(r['objective'])}</td><td>{esc(r['generated_by'])}</td><td>{'ja' if r['external_ai_used'] else 'nein'}</td></tr>" for r in briefs) or '<tr><td colspan="4">Noch kein Ermittlungsbrief.</td></tr>'
    opsec_table = "".join(f"<tr><td>{esc(r['created_at'])}</td><td>{esc(r['action_type'])}</td><td>{esc(r['risk_level'])}</td><td>{'blockiert' if r['blocked'] else 'freigegeben'}</td></tr>" for r in opsec) or '<tr><td colspan="4">Noch keine OPSEC-Prüfung.</td></tr>'
    return f'''
<div class="notice"><b>Build 139 · Identity Resolution & Safe Face Analysis:</b> Identitätsvorschläge werden ausschließlich aus erklärbaren nichtbiometrischen Ankern bewertet. Automatische Zusammenführung, Gesichtsmatching, biometrische Templates und autonome Identitätsentscheidungen sind technisch deaktiviert.</div>
<div class="metrics"><div class="metric"><div class="label">Identitätskandidaten</div><div class="value">{esc(identity['candidate_count'])}</div></div><div class="metric"><div class="label">Offene Prüfungen</div><div class="value">{esc(identity['open_count'])}</div></div><div class="metric"><div class="label">Automatische Merges</div><div class="value">0</div></div><div class="metric"><div class="label">Gesichtsmerkmale im Score</div><div class="value">0</div></div></div>
<div class="two-col"><div class="panel"><h2>Identitätskandidat anlegen</h2><form method="post" action="/identity139/candidate"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson</label><select name="target_id" required>{target_options}</select></div><div class="field"><label>Kandidatenbezeichnung</label><input name="label" required placeholder="Treffername / Fundstelle"></div><div class="form-grid"><div class="field"><label>Name / Aliasse</label><input name="name"></div><div class="field"><label>Geburtsdatum/-jahr</label><input name="birth_date"></div><div class="field"><label>Beruf</label><input name="occupation"></div><div class="field"><label>Organisation</label><input name="organization"></div><div class="field"><label>Ort</label><input name="location"></div><div class="field"><label>Benutzername</label><input name="username"></div><div class="field"><label>E-Mail</label><input name="email"></div><div class="field"><label>Domain</label><input name="domain"></div></div><div class="field"><label>Quellenreferenzen, durch Komma getrennt</label><input name="source_refs"></div><button>Kandidat speichern</button></form></div>
<div class="panel"><h2>Lokaler AI-Ermittlungsbrief</h2><p>Ordnet bestätigte Fakten, Hypothesen, Widersprüche, Beleglücken, nächste Schritte und Bias-Kontrollen. Es findet kein externer Modellaufruf statt.</p><form method="post" action="/identity139/brief"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson optional</label><select name="target_id">{target_options}</select></div><div class="field"><label>Ermittlungsziel</label><textarea name="objective" rows="4" required></textarea></div><button>Lokalen Ermittlungsbrief erzeugen</button></form></div></div>
<div class="panel"><h2>Identitätskandidaten</h2>{''.join(candidate_rows) if candidate_rows else '<div class="empty">Noch keine Identitätskandidaten.</div>'}</div>
<div class="two-col"><div class="panel"><h2>OPSEC-Prüfung</h2><form method="post" action="/identity139/opsec"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson optional</label><select name="target_id">{target_options}</select></div><div class="field"><label>Aktion</label><select name="action_type"><option value="web_search">Webrecherche</option><option value="reverse_image_search">Reverse-Image-Recherche</option><option value="external_ai_assist">Externe AI-Assistenz</option><option value="export">Export</option><option value="local_face_detection">Lokale Gesichtsbereichsanalyse</option><option value="face_matching">Gesichtsabgleich – wird blockiert</option><option value="biometric_identification">Biometrische Identifizierung – wird blockiert</option></select></div><div class="field"><label>Zweck</label><input name="purpose" required></div><div class="field"><label>Rechtsgrundlage</label><input name="legal_basis" required></div><div class="field"><label>Datenklassen</label><input name="data_classes" placeholder="name, location, facial_image"></div><button>OPSEC bewerten</button></form></div><div class="panel"><h2>Sicherheitsgrenze 139</h2><ul><li>Keine Gesichts-Embeddings oder biometrischen Templates</li><li>Kein 1:1- oder 1:N-Gesichtsabgleich</li><li>Keine Emotionserkennung oder demografische Klassifizierung</li><li>Keine automatischen Bild-Uploads</li><li>Keine autonome Identitätsfusion</li></ul></div></div>
<div class="two-col"><div class="panel"><h2>Letzte Ermittlungsbriefs</h2><div class="table-wrap"><table><thead><tr><th>Zeit</th><th>Ziel</th><th>Engine</th><th>Extern</th></tr></thead><tbody>{brief_table}</tbody></table></div></div><div class="panel"><h2>Letzte OPSEC-Prüfungen</h2><div class="table-wrap"><table><thead><tr><th>Zeit</th><th>Aktion</th><th>Risiko</th><th>Status</th></tr></thead><tbody>{opsec_table}</tbody></table></div></div></div>
'''
