from __future__ import annotations

import json
from typing import Any, Callable


def render_phase4_operations(ctx: Any, case_id: str, csrf: str, *, esc: Callable[[Any], str], table: Callable[..., str]) -> str:
    svc = ctx.phase4_operations_134
    data = svc.dashboard(case_id)
    b135 = ctx.build135.dashboard(case_id)
    b136 = ctx.build136.dashboard(case_id)
    b137 = ctx.build137.dashboard(case_id)
    b138 = ctx.build138.dashboard(case_id)
    b139 = ctx.build139.dashboard(case_id)
    b140 = ctx.build140.dashboard(case_id)
    b141 = ctx.build141.dashboard(case_id)
    b142 = ctx.build142.dashboard(case_id)
    b143 = ctx.build143.dashboard(case_id)
    browser136 = b136.get("browser", {})
    photos136 = b136.get("photos", {})
    status = data["status"]
    packages = data["packages"]
    source_rows = [{"label": item.get("label", ""), "source_key": item.get("source_key", ""), "execution_mode": item.get("execution_mode", ""), "health": (item.get("health") or {}).get("status", "offline"), "auth_profile": item.get("auth_profile", ""), "candidate_only": item.get("candidate_only", 1)} for item in b135.get("sources", [])]
    browser_rows = b135.get("browser", {}).get("orders", [])
    package_rows = [
        {
            "package_id": item["package_id"],
            "package_name": item["package_name"],
            "provider_key": item["provider_key"],
            "package_version": item["package_version"],
            "trust_state": item["trust_state"],
            "execution_state": item["execution_state"],
            "enabled": item["enabled"],
        }
        for item in packages
    ]
    target_rows = ctx.targets.list_targets(case_id)
    target_options = "".join(
        f'<option value="{esc(item["target_id"])}">{esc(item["name"])}</option>' for item in target_rows
    )
    package_options = "".join(
        f'<option value="{esc(item["package_id"])}">{esc(item["package_name"])} · {esc(item["trust_state"])}</option>'
        for item in packages
    )
    advice_rows = []
    for item in data["advice"]:
        content = json.loads(item.get("content_json") or "{}")
        advice_rows.append({
            "created_at": item.get("created_at", ""),
            "advice_id": item.get("advice_id", ""),
            "trust_state": item.get("trust_state", ""),
            "review_status": item.get("review_status", ""),
            "recommendations": len(content.get("recommended_connectors") or []),
        })
    return f'''
<div class="notice"><b>Phase 4 · Operational Intelligence & Connector Trust:</b> Build 143 verbindet den operativen Connector-Vertrauensrahmen mit Live-Health, Contract-Change-Erkennung, lokalem AI Source Routing und fallgebundenem Firefox-Tab-Routing. Drittcode-Ausführung und autonome Providerfreigaben bleiben deaktiviert.</div>
<div class="metrics"><div class="metric"><div class="label">Connectorpakete</div><div class="value">{esc(status["package_count"])}</div></div><div class="metric"><div class="label">Vertrauenswürdig</div><div class="value">{esc(status["trusted_packages"])}</div></div><div class="metric"><div class="label">Quarantäne</div><div class="value">{esc(status["quarantined_packages"])}</div></div><div class="metric"><div class="label">Externe AI-Aktionen</div><div class="value">{esc(status["max_external_ai_actions"])}</div></div></div>
<div class="two-col"><div class="panel"><h2>Runtime Preflight</h2><p>Prüft Launcher, Python, Abhängigkeiten, Schreibrechte, Loopback, Firefox, Datenbank, Dienste und Connector-Trust. Reparaturen bleiben advisory-only.</p><form method="post" action="/operations/preflight"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><p><button>Preflight ausführen</button></p></form></div>
<div class="panel"><h2>Offline Connector Contract</h2><form method="post" action="/operations/contract"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Paket</label><select name="package_id" required>{package_options}</select></div><p><button>Contract prüfen</button></p></form></div></div>
<div class="panel"><h2>Lokaler AI Connector Router</h2><p>Priorisiert nur vertrauenswürdige Connectoren anhand geprüfter Ankertypen, Providerzustand und Datenminimierung. Es wird keine Suche ausgeführt.</p><form method="post" action="/operations/advice"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson</label><select name="target_id" required>{target_options}</select></div><div class="field"><label>Ermittlungsziel</label><textarea name="objective" rows="3" required></textarea></div><p><button>Connector-Empfehlung erzeugen</button></p></form></div>
<div class="two-col"><div class="panel"><h2>Trusted Signer hinzufügen</h2><form method="post" action="/operations/signer"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Bezeichnung</label><input name="label" required></div><div class="field"><label>Ed25519 Public Key, Base64 (32 Bytes)</label><textarea name="public_key_b64" rows="3" required></textarea></div><div class="field"><label>Freigabephrase</label><input name="confirmation" placeholder="TRUST SIGNER" required></div><p><button>Signer vertrauen</button></p></form></div>
<div class="panel"><h2>Externes Manifest registrieren</h2><p>Nur Metadaten werden geprüft. Kein Python-, JavaScript- oder Binärcode wird geladen oder ausgeführt.</p><form method="post" action="/operations/manifest"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Manifest JSON</label><textarea name="manifest_json" rows="8" required></textarea></div><div class="field"><label>Signer-Fingerprint, optional</label><input name="signer_fingerprint" maxlength="64"></div><div class="field"><label>Ed25519-Signatur Base64, optional</label><textarea name="signature_b64" rows="3"></textarea></div><p><button>Manifest prüfen und registrieren</button></p></form></div></div>
<div class="panel"><h2>Connector-Paketkatalog</h2>{table(package_rows, [("package_name","Paket"),("provider_key","Provider"),("package_version","Version"),("trust_state","Trust"),("execution_state","Ausführung"),("enabled","Aktiv")])}</div>
<div class="two-col"><div class="panel"><h2>Letzte Preflights</h2>{table(data["preflight_runs"], [("created_at","Zeit"),("status","Status"),("score","Score"),("blocker_count","Blocker"),("warning_count","Warnungen")])}</div><div class="panel"><h2>Letzte Contracts</h2>{table(data["contract_runs"], [("created_at","Zeit"),("provider_key","Provider"),("status","Status"),("blocker_count","Blocker"),("warning_count","Warnungen")])}</div></div>
<div class="panel"><h2>AI Connector Advice</h2>{table(advice_rows, [("created_at","Zeit"),("advice_id","ID"),("trust_state","Trust"),("review_status","Review"),("recommendations","Empfehlungen")])}</div>
<hr><div class="notice"><b>Build 135 · Source Intelligence & Persistent Firefox Tabs:</b> {esc(b135["source_count"])} kontrollierte Quellenzugänge, davon {esc(b135["native_source_count"])} native Adapter und {esc(b135["guided_source_count"])} geführte offizielle Register. Jeder Treffer bleibt candidate_only und jede Ausführung benötigt eine ausdrückliche Freigabe.</div>
<div class="metrics"><div class="metric"><div class="label">Quellenzugänge</div><div class="value">{esc(b135["source_count"])}</div></div><div class="metric"><div class="label">Native Adapter</div><div class="value">{esc(b135["native_source_count"])}</div></div><div class="metric"><div class="label">Person Profile Pro</div><div class="value">{esc(b135["profile_count"])}</div></div><div class="metric"><div class="label">Firefox Companion</div><div class="value">{"aktiv" if b135.get("browser", {}).get("companion_active") else "nicht aktiv"}</div></div></div>
<div class="two-col"><div class="panel"><h2>Live Provider Health</h2><p>Sendet ausschließlich feste, datensparsame Health-Probes. Keine Personenanker werden übertragen.</p><form method="post" action="/operations/build135-health"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><p><button>Health & Contract prüfen</button></p></form></div>
<div class="panel"><h2>AI Source Routing 2.0</h2><p>Erzeugt lokale, candidate-only Empfehlungen mit höchstens drei minimal erforderlichen Ankern. Keine Quelle wird automatisch ausgeführt.</p><form method="post" action="/operations/build135-route"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson</label><select name="target_id" required>{target_options}</select></div><div class="field"><label>Ermittlungsziel</label><textarea name="objective" rows="3" required></textarea></div><p><button>Quellenroute erzeugen</button></p></form></div></div>
<div class="panel"><h2>Attribute Contradiction Analysis</h2><form method="post" action="/operations/build135-contradictions"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson</label><select name="target_id" required>{target_options}</select></div><p><button>Profil auf Widersprüche prüfen</button></p></form>{table(b135.get("recent_contradictions", []), [("created_at","Zeit"),("contradiction_type","Typ"),("severity","Schwere"),("summary","Zusammenfassung"),("status","Status")])}</div>
<div class="panel"><h2>Quellenkatalog Build 135</h2>{table(source_rows, [("label","Quelle"),("source_key","Schlüssel"),("execution_mode","Modus"),("health","Health"),("auth_profile","Authentifizierung"),("candidate_only","Candidate-only")])}</div>
<div class="two-col"><div class="panel"><h2>Firefox-Tab-Router</h2><p>Bestehende Fall-Sitzung: neue Recherche als Tabs; Fallback ausschließlich mit demselben isolierten Firefox-Profil.</p>{table(browser_rows, [("created_at","Zeit"),("order_id","Auftrag"),("dispatch_mode","Modus"),("status","Status"),("engines","Engines")])}</div><div class="panel"><h2>Letzte Source-Routen</h2>{table(b135.get("recent_routes", []), [("created_at","Zeit"),("route_id","Route"),("target_id","Ziel"),("objective","Zweck"),("review_status","Review")])}</div></div>
<hr><div class="notice"><b>Build 136 · Windows/Firefox Stabilization:</b> Der sichere Fail-closed-Router bleibt erhalten, erhält jetzt aber einen nachvollziehbaren Sitzungszustand, kontrollierte Wiederherstellung und eine lokale Fotoakte mit Drag-and-drop.</div>
<div class="metrics"><div class="metric"><div class="label">Firefox-Zustand</div><div class="value">{esc(browser136.get("state", "unknown"))}</div></div><div class="metric"><div class="label">Companion</div><div class="value">{"aktiv" if browser136.get("companion_active") else "nicht aktiv"}</div></div><div class="metric"><div class="label">Offene Tab-Aufträge</div><div class="value">{esc(browser136.get("pending_orders", 0))}</div></div><div class="metric"><div class="label">Fotos in Akte</div><div class="value">{esc(photos136.get("count", 0))}</div></div></div>
<div class="two-col"><div class="panel"><h2>Build-136-Runtime-Diagnose</h2><p>{esc(browser136.get("summary", ""))}</p><p class="footer">Firefox: {esc(browser136.get("firefox_path") or "nicht gefunden")} · Heartbeat-Alter: {esc(browser136.get("heartbeat_age_seconds"))} Sekunden · Companion-Paket: {"vollständig" if browser136.get("companion_package_ok") else "unvollständig"}</p><form method="post" action="/operations/build136-diagnostics"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><p><button>Runtime und Fallbrowser prüfen</button></p></form>{table(b136.get("diagnostics", []), [("created_at","Zeit"),("status","Status"),("score","Score"),("blocker_count","Blocker"),("warning_count","Warnungen")])}</div>
<div class="panel"><h2>Geführte Firefox-Wiederherstellung</h2><p>Destruktive oder mehrdeutige Browseraktionen werden nicht automatisch ausgeführt. Für Wiederherstellungen muss das isolierte Fallfenster nachweislich vollständig geschlossen sein.</p><form method="post" action="/operations/build136-repair"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Aktion</label><select name="action"><option value="expire_pending_orders">Offene Tab-Aufträge verwerfen</option><option value="clear_failed_orders">Fehlgeschlagene Aufträge archivieren</option><option value="prepare_registered_recovery">Registrierte Sitzung kontrolliert wiederherstellen</option><option value="reset_incomplete_setup">Unvollständige Ersteinrichtung zurücksetzen</option></select></div><div class="field"><label>Bestätigung bei Browser-Recovery</label><input name="confirmation" placeholder="FALLBROWSER GESCHLOSSEN"></div><p><button>Ausgewählte Reparatur ausführen</button></p></form></div></div>
<div class="panel"><h2>Fotoakte-Grundlage</h2><p>Lokale Bilddateien werden unverändert, gehasht und candidate-only gespeichert. Webbild-URLs werden aus OPSEC-Gründen nur referenziert, nicht automatisch heruntergeladen.</p><p><a class="button" href="/?tab=photos&case_id={esc(case_id)}">Fotoakte öffnen</a></p></div>

<hr><div class="notice"><b>Build 137 · Geführte Ermittlungsabläufe und Fotorecherche:</b> Ermittlungsziele werden in sieben prüfbare Stufen zerlegt. Bildanalyse, Ähnlichkeits-Hashes und Reverse-Image-Research bleiben lokal vorbereitet, kandidatbasiert und ohne automatischen Upload.</div>
<div class="metrics"><div class="metric"><div class="label">Ermittlungsworkflows</div><div class="value">{esc(b137.get("workflow_count", 0))}</div></div><div class="metric"><div class="label">Analysierte Fotos</div><div class="value">{esc((b137.get("photos") or {}).get("analyzed_count", 0))}</div></div><div class="metric"><div class="label">Recherchekopien</div><div class="value">{esc((b137.get("photos") or {}).get("copy_count", 0))}</div></div><div class="metric"><div class="label">Automatische Identitätsaussagen/Uploads</div><div class="value">0 / 0</div></div></div>
<div class="two-col"><div class="panel"><h2>Ermittlungsworkflow</h2><p>Namensvarianten, Quellenstufen, Gegenhypothesen und Aufgabenstatus werden reproduzierbar dokumentiert.</p><p><a class="button" href="/?tab=workflow137&case_id={esc(case_id)}">Workflows öffnen</a></p></div><div class="panel"><h2>Fotorecherche</h2><p>Original, bereinigte Recherchekopie, Anbieterfreigabe und manueller Upload bleiben strikt getrennt.</p><p><a class="button" href="/?tab=photos&case_id={esc(case_id)}">Fotorecherche öffnen</a></p></div></div>



<hr><div class="notice"><b>Build 138 · Evidence Graph & Advanced Photo Research:</b> Feststellungen, Quellen, Belegketten und Fototreffer werden getrennt modelliert. Quellenabhängigkeit, Zirkularität und zeitliche Konflikte werden lokal geprüft; automatische Identitätsaussagen und Bilduploads bleiben deaktiviert.</div>
<div class="metrics"><div class="metric"><div class="label">Evidence Nodes</div><div class="value">{esc((b138.get("evidence") or {}).get("node_count", 0))}</div></div><div class="metric"><div class="label">Aussagen</div><div class="value">{esc((b138.get("evidence") or {}).get("assertion_count", 0))}</div></div><div class="metric"><div class="label">Quellen</div><div class="value">{esc((b138.get("evidence") or {}).get("source_count", 0))}</div></div><div class="metric"><div class="label">Fototreffer / Varianten</div><div class="value">{esc((b138.get("photos") or {}).get("result_count", 0))} / {esc((b138.get("photos") or {}).get("variant_count", 0))}</div></div></div>
<div class="two-col"><div class="panel"><h2>Evidence Graph</h2><p>Quellen, Aussagen, Provenienz, Unabhängigkeitsgruppen und Integritätswarnungen werden nachvollziehbar dokumentiert.</p><p><a class="button" href="/?tab=evidence138&case_id={esc(case_id)}">Evidence Graph öffnen</a></p></div><div class="panel"><h2>Erweiterte Fotorecherche</h2><p>Recherchevarianten, Provider-Serien, manuell dokumentierte Treffer, lokale Bildvergleiche und candidate-only Cluster.</p><p><a class="button" href="/?tab=photos&case_id={esc(case_id)}">Fotorecherche öffnen</a></p></div></div>


<hr><div class="notice"><b>Build 139 · Explainable Identity, AI Assistance & OPSEC:</b> Identitätskandidaten werden aus nichtbiometrischen Merkmalen und Quellenkontext bewertet. Die lokale Gesichtsbereichsanalyse erzeugt nur qualitätsgeprüfte, metadatenfreie Rechercheausschnitte; Gesichtsmatching und biometrische Templates sind technisch deaktiviert.</div>
<div class="metrics"><div class="metric"><div class="label">Identitätskandidaten</div><div class="value">{esc((b139.get("identity") or {}).get("candidate_count", 0))}</div></div><div class="metric"><div class="label">Lokale AI-Briefs</div><div class="value">{esc((b139.get("assistant") or {}).get("brief_count", 0))}</div></div><div class="metric"><div class="label">Gesichtsbereiche</div><div class="value">{esc((b139.get("photos") or {}).get("face_count", 0))}</div></div><div class="metric"><div class="label">Templates / Face Matches / Auto-Merges</div><div class="value">0 / 0 / 0</div></div></div>
<div class="two-col"><div class="panel"><h2>Identity Lab 139</h2><p>Erklärbare Merkmalsgewichte, harte Ausschlusskonflikte, manuelle Entscheidungen, Bias-Kontrollen und datensparsame Offenlegungspläne.</p><p><a class="button" href="/?tab=identity139&case_id={esc(case_id)}">Identity Lab öffnen</a></p></div><div class="panel"><h2>Sichere Gesichtsanalyse</h2><p>Lokale Gesichtsbereichserkennung, Schärfe-, Helligkeits- und Kontrastprüfung sowie manuell freigegebene Reverse-Image-Recherche ohne biometrischen Vergleich.</p><p><a class="button" href="/?tab=photos&case_id={esc(case_id)}">Fotoanalyse öffnen</a></p></div></div>
<hr><div class="notice"><b>Build 140 · Evidence-Grounded AI, OPSEC Planning & Image Intelligence:</b> Aussagen werden mit Belegreferenzen, Unsicherheit, Gegenhypothesen und Prompt-Injection-Warnungen erzeugt. OPSEC-Aktionspläne und minimierte Offenlegungspakete bleiben manuell, fallgebunden und ohne automatische Außenaktion.</div>
<div class="metrics"><div class="metric"><div class="label">Build-140-Analysen</div><div class="value">{esc((b140.get("assistant") or {}).get("analysis_count", 0))}</div></div><div class="metric"><div class="label">Zitierbare Aussagen</div><div class="value">{esc((b140.get("assistant") or {}).get("claim_count", 0))}</div></div><div class="metric"><div class="label">Technische Bildanalysen</div><div class="value">{esc((b140.get("images") or {}).get("analysis_count", 0))}</div></div><div class="metric"><div class="label">Extern / biometrisch / autonom</div><div class="value">0 / 0 / 0</div></div></div>
<div class="two-col"><div class="panel"><h2>AI Analyst 140</h2><p>Beleggebundene Analyse, Gegenhypothesen, offene Fragen, priorisierte nächste Schritte und manuell prüfbare Aussagen.</p><p><a class="button" href="/?tab=assistant140&case_id={esc(case_id)}">AI Analyst öffnen</a></p></div><div class="panel"><h2>Image Intelligence 140</h2><p>Lokale Qualitäts-, Metadaten-, Rekodierungs- und Variantenindikatoren ohne Manipulations- oder Identitätsbehauptung.</p><p><a class="button" href="/?tab=photos&case_id={esc(case_id)}">Bildanalyse öffnen</a></p></div></div>
<hr><div class="notice"><b>Build 141 · Source Quality, Change Watch & Efficient Operations:</b> Quellen werden nach Autorität, Primärnähe, Unabhängigkeit, Aktualität, Stabilität und Transparenz bewertet. Änderungsereignisse wirken auf AI-Unsicherheit und Priorisierung; OPSEC-Fenster besitzen Ablaufzeit und Aktionsbudget.</div>
<div class="metrics"><div class="metric"><div class="label">Bewertete Quellen</div><div class="value">{esc((b141.get("metrics") or {}).get("source_count", 0))}</div></div><div class="metric"><div class="label">Offene Quellenänderungen</div><div class="value">{esc((b141.get("metrics") or {}).get("open_changes", 0))}</div></div><div class="metric"><div class="label">Quellenrisiken</div><div class="value">{esc((b141.get("metrics") or {}).get("open_risks", 0))}</div></div><div class="metric"><div class="label">Auto-AI / Auto-Upload / Biometrie</div><div class="value">0 / 0 / 0</div></div></div>
<div class="two-col"><div class="panel"><h2>Qualität & Effizienz 141</h2><p>Change-aware AI, Quellenänderungsprüfung, zeitlich begrenzte OPSEC-Fenster und reversible Workflow-Dry-Runs.</p><p><a class="button" href="/?tab=quality141&case_id={esc(case_id)}">Build 141 öffnen</a></p></div><div class="panel"><h2>Fotoresearch 141</h2><p>Trefferqualität, Ursprungssuche, Anbieterdiversität und Deduplizierung ohne automatischen Upload oder Personenidentifizierung.</p><p><a class="button" href="/?tab=photos&case_id={esc(case_id)}">Fotorecherche öffnen</a></p></div></div>
<hr><div class="notice"><b>Build 142 · Professional Reports & Immutable Exports:</b> Ermittlungsberichte werden aus einem eingefrorenen Belegsnapshot erzeugt, redigiert, im Vier-Augen-Prinzip geprüft und als unveränderliche HTML-, PDF- und JSON-Releasefassung mit Hashmanifest veröffentlicht.</div>
<div class="metrics"><div class="metric"><div class="label">Berichte</div><div class="value">{esc((b142.get("metrics") or {}).get("reports", 0))}</div></div><div class="metric"><div class="label">Reviewbereit</div><div class="value">{esc((b142.get("metrics") or {}).get("review_ready", 0))}</div></div><div class="metric"><div class="label">Releasefassungen</div><div class="value">{esc((b142.get("metrics") or {}).get("released", 0))}</div></div><div class="metric"><div class="label">Integritätsfehler</div><div class="value">{esc((b142.get("metrics") or {}).get("integrity_failures", 0))}</div></div></div>
<div class="two-col"><div class="panel"><h2>Berichte 142</h2><p>Acht Berichtstypen, Redaktionsprofile, Zitierabdeckung, Quellenregister, Vier-Augen-Review und kontrollierte Freigabe.</p><p><a class="button" href="/?tab=reports142&case_id={esc(case_id)}">Berichtszentrale öffnen</a></p></div><div class="panel"><h2>Revisionssichere Exporte</h2><p>HTML, PDF, JSON und Manifest werden pro Release gehasht. Jede spätere Dateiänderung wird durch die Integritätsprüfung erkannt.</p><p class="footer">Automatische Exporte: 0 · Externe AI-Aufrufe: 0 · Automatische Identitätsaussagen: 0</p></div></div>

<hr><div class="notice"><b>Build 143 · Controlled Collaboration & Research Personas:</b> Fallgebundene Research-Personas, manuell provisionierte Alias-Konten, freigabepflichtige Egress-Profile und temporäre Firefox-Sitzungen erweitern die OPSEC, ohne automatische Kontoerstellung, Login-Automation oder ein Versprechen der Unverfolgbarkeit.</div>
<div class="metrics"><div class="metric"><div class="label">Personas</div><div class="value">{esc((b143.get("metrics") or {}).get("personas", 0))}</div></div><div class="metric"><div class="label">Alias-Konten</div><div class="value">{esc((b143.get("metrics") or {}).get("accounts", 0))}</div></div><div class="metric"><div class="label">Egress-Profile</div><div class="value">{esc((b143.get("metrics") or {}).get("egress_profiles", 0))}</div></div><div class="metric"><div class="label">Aktive Sitzungen</div><div class="value">{esc((b143.get("metrics") or {}).get("active_sessions", 0))}</div></div></div>
<div class="two-col"><div class="panel"><h2>Research Personas</h2><p>Synthetische oder organisationsgebundene Rechercheidentitäten werden fallbezogen angelegt, im Vier-Augen-Prinzip geprüft und zeitlich begrenzt verwendet. Konten müssen außerhalb von EagleEye manuell und rechtmäßig provisioniert werden.</p><p><a class="button" href="/?tab=security143&case_id={esc(case_id)}">OPSEC &amp; Personas öffnen</a></p></div><div class="panel"><h2>Egress Sessions</h2><p>Temporäre Firefox-Profile, WebRTC-/Geolocation-Härtung, Remote-DNS-Prüfung, Aktionsbudgets und unabhängige Freigaben begrenzen die Sitzung.</p><p class="footer">Automatische Kontoerstellung: 0 · Automatische Logins: 0 · Anti-Bot-Umgehung: 0 · Garantie der Unverfolgbarkeit: nein</p></div></div>
'''
