from __future__ import annotations

from typing import Any, Callable

from .photo138_views import render_photo138


def render_photo139(ctx: Any, case_id: str, csrf: str, *, esc: Callable[[Any], str]) -> str:
    data = ctx.build139.photo_dashboard(case_id)
    base = ctx.build136.photo_dashboard(case_id)
    targets = ctx.targets.list_targets(case_id)
    target_options = '<option value="">Zielperson auswählen</option>' + ''.join(f'<option value="{esc(t["target_id"])}">{esc(t["name"])}</option>' for t in targets)
    asset_options = '<option value="">Lokales Foto auswählen</option>' + ''.join(f'<option value="{esc(p["asset_id"])}">{esc(p.get("title") or p.get("filename") or p["asset_id"])}</option>' for p in base.get("photos", []) if p.get("source_kind") == "local_file")
    detection_cards = []
    for row in data["detections"]:
        detection_cards.append(f'''<article class="photo-card"><img class="photo-thumb" src="{esc(row['crop_url'])}" alt="Metadatenfreier Gesichtsausschnitt"><div class="photo-body"><h3>{esc(row.get('asset_title') or 'Gesichtsbereich')}</h3><div class="inline"><span class="badge">Qualität: {esc(row['quality_band'])}</span><span class="badge candidate">keine Identitätsaussage</span></div><p>{esc(row['research_suitability'])}</p><div class="footer">Detektor: {esc(row['detector_name'])} · Box: {esc(row['width_px'])}×{esc(row['height_px'])} · Schärfe: {esc(round(float(row['blur_variance']), 1))}<br>Biometrisches Template: nein · Gesichtsabgleich: nein</div><form method="post" action="/photos139/face-runs"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="detection_id" value="{esc(row['detection_id'])}"><div class="field"><label>Zweck</label><input name="purpose" value="Öffentliche Fundstellen dieses metadatenfreien Bildausschnitts manuell prüfen" required></div><div class="inline"><label><input type="checkbox" name="provider_google_lens" value="1" checked>Google Lens</label><label><input type="checkbox" name="provider_bing_visual" value="1">Bing</label><label><input type="checkbox" name="provider_tineye" value="1">TinEye</label><label><input type="checkbox" name="provider_yandex_images" value="1">Yandex</label></div><div class="field"><label>Freigabephrase</label><input name="confirmation" placeholder="GESICHTSAUSSCHNITT-RECHERCHE FREIGEBEN" required></div><button class="small">Manuelle Recherche vorbereiten</button></form></div></article>''')
    run_rows = []
    for row in data["runs"]:
        run_rows.append(f'''<tr><td>{esc(row['provider_label'])}</td><td>{esc(row['status'])}</td><td><a class="button small ghost" href="/api/photo139/face/{esc(row['detection_id'])}?case_id={esc(case_id)}">Ausschnitt</a></td><td><form method="post" action="/photos139/face-launch"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="run_id" value="{esc(row['run_id'])}"><button class="small">Anbieter öffnen</button></form></td></tr>''')
    link_rows = []
    for row in data["links"]:
        link_rows.append(f"<tr><td>{esc(row['target_name'])}</td><td>{esc(row['asset_title'])}</td><td>{esc(row['support_score'])}</td><td>{esc(row['conflict_score'])}</td><td>{esc(row['review_status'])}</td><td>nein</td></tr>")
    header = f'''
<div class="notice"><b>Build 139 · Verfeinerte Foto- und Personenanalyse:</b> EagleEye erkennt lokal Gesichtsbereiche und bewertet ausschließlich Bildqualität und Rechercheeignung. Es werden keine biometrischen Templates, Gesichts-Embeddings, Personenabgleiche, Emotionen, Alter, Geschlecht oder andere sensible Kategorien abgeleitet.</div>
<div class="metrics"><div class="metric"><div class="label">Gesichtsbereiche</div><div class="value">{esc(data['face_count'])}</div></div><div class="metric"><div class="label">Manuelle Rechercheläufe</div><div class="value">{esc(data['run_count'])}</div></div><div class="metric"><div class="label">Foto-Person-Hypothesen</div><div class="value">{esc(data['link_count'])}</div></div><div class="metric"><div class="label">Biometrische Templates / Matches</div><div class="value">0 / 0</div></div></div>
<div class="two-col"><div class="panel"><h2>Lokale Gesichtsbereichsanalyse</h2><form method="post" action="/photos139/detect"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Lokales Foto</label><select name="asset_id" required>{asset_options}</select></div><button>Gesichtsbereiche erkennen und Qualität prüfen</button></form><p class="footer">Verfügbarkeit lokaler Detektor: {'ja' if data['face_detection_available'] else 'nein – OpenCV-Laufzeit prüfen'}.</p></div>
<div class="panel"><h2>Nichtbiometrische Foto-Person-Zuordnung</h2><form method="post" action="/photos139/person-link"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson</label><select name="target_id" required>{target_options}</select></div><div class="field"><label>Foto</label><select name="asset_id" required>{asset_options}</select></div><div class="inline"><label><input type="checkbox" name="basis_official_profile_context" value="1">Offizieller Profilkontext</label><label><input type="checkbox" name="basis_caption_names_person" value="1">Bildunterschrift nennt Person</label><label><input type="checkbox" name="basis_source_page_names_person" value="1">Quellseite nennt Person</label><label><input type="checkbox" name="basis_exact_image_provenance" value="1">Exakte Bildprovenienz</label><label><input type="checkbox" name="basis_timeline_compatible" value="1">Zeitlich vereinbar</label><label><input type="checkbox" name="basis_caption_names_other_person" value="1">Andere Person genannt</label></div><button>Zuordnung als Hypothese bewerten</button></form></div></div>
<div class="panel"><h2>Erkannte Gesichtsbereiche</h2><div class="photo-grid">{''.join(detection_cards) if detection_cards else '<div class="empty">Noch keine Gesichtsbereiche analysiert.</div>'}</div></div>
<div class="two-col"><div class="panel"><h2>Gesichtsausschnitt-Rechercheläufe</h2><div class="table-wrap"><table><thead><tr><th>Anbieter</th><th>Status</th><th>Ausschnitt</th><th>Aktion</th></tr></thead><tbody>{''.join(run_rows) if run_rows else '<tr><td colspan="4">Noch keine Läufe.</td></tr>'}</tbody></table></div></div><div class="panel"><h2>Foto-Person-Hypothesen</h2><div class="table-wrap"><table><thead><tr><th>Person</th><th>Foto</th><th>Support</th><th>Konflikt</th><th>Status</th><th>Face Match</th></tr></thead><tbody>{''.join(link_rows) if link_rows else '<tr><td colspan="6">Noch keine Zuordnungshypothesen.</td></tr>'}</tbody></table></div></div></div>
<hr>
'''
    return header + render_photo138(ctx, case_id, csrf, esc=esc)
