from __future__ import annotations

from typing import Any, Callable

from .photo137_views import render_photo137


def render_photo138(ctx: Any, case_id: str, csrf: str, *, esc: Callable[[Any], str]) -> str:
    base = render_photo137(ctx, case_id, csrf, esc=esc)
    photos = [row for row in ctx.build136.list_photos(case_id=case_id, limit=300) if row["source_kind"] == "local_file"]
    old = ctx.build137.photo_dashboard(case_id)
    data = ctx.build138.photo_dashboard(case_id)
    photo_options = ''.join(f'<option value="{esc(row["asset_id"])}">{esc(row.get("title") or row.get("original_filename"))}</option>' for row in photos) or '<option value="">Zuerst lokales Foto hinzufügen</option>'
    result_asset_options = '<option value="">Nur Quellenreferenz</option>' + ''.join(f'<option value="{esc(row["asset_id"])}">{esc(row.get("title") or row.get("original_filename"))}</option>' for row in photos)
    source_options = ''.join(f'<option value="variant:{esc(row["variant_id"])}">Variante 138 · {esc(row["label"])} · {esc(row["variant_mode"])}</option>' for row in data["variants"] if row["status"] == "ready")
    source_options += ''.join(f'<option value="copy137:{esc(row["copy_id"])}">Kopie 137 · {esc(row["filename"])}</option>' for row in old["copies"] if row["status"] == "ready")
    source_options = source_options or '<option value="">Zuerst Recherchekopie oder Variante erzeugen</option>'
    run_options = ''.join(f'<option value="build138:{esc(row["run_id"])}">Build 138 · {esc(row["provider_label"])} · {esc(row["status"])}</option>' for row in data["runs"])
    run_options += ''.join(f'<option value="build137:{esc(row["job_id"])}">Build 137 · {esc(row["provider_label"])} · {esc(row["status"])}</option>' for row in old["jobs"])
    run_options = run_options or '<option value="">Zuerst Fotorecherche-Lauf anlegen</option>'
    run_cards = []
    for row in data["runs"]:
        statuses = ''.join(f'<option value="{esc(status)}"{" selected" if status == row["status"] else ""}>{esc(status)}</option>' for status in ("prepared", "provider_opened", "uploaded_manually", "results_review", "completed", "cancelled"))
        run_cards.append(f'''<div class="intake-card"><div class="intake-head"><div><h3>{esc(row['provider_label'])}</h3><p>{esc(row['purpose'])}</p></div><span class="badge candidate">{esc(row['status'])}</span></div><p class="footer">Quelle: {esc(row['disclosure'].get('filename'))} · Metadaten entfernt · automatischer Upload: 0</p><div class="inline"><a class="button ghost small" href="{esc(row['download_url'])}">Variante bereitstellen</a><form method="post" action="/photos138/run-launch"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="run_id" value="{esc(row['run_id'])}"><button class="small">Anbieter öffnen</button></form><form method="post" action="/photos138/run-status"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="run_id" value="{esc(row['run_id'])}"><select name="status">{statuses}</select><input name="result_note" value="{esc(row.get('result_note') or '')}" placeholder="Trefferlage"><button class="small ghost">Speichern</button></form></div></div>''')
    result_cards = []
    for row in data["results"]:
        cmp = row.get("comparison") or {}
        band = cmp.get("image_relation_band") or "nicht lokal verglichen"
        result_cards.append(f'''<div class="intake-card"><div class="intake-head"><div><h3>{esc(row.get('page_title') or row['page_url'])}</h3><p>{esc(row['page_url'])}</p></div><span class="badge candidate">{esc(row['review_status'])}</span></div><p>Trefferart: <b>{esc(row['result_kind'])}</b> · Dateivergleich: <b>{esc(band)}</b> · Identitätsaussage: <b>nein</b></p><p class="footer">{esc(row.get('notes') or '')}</p><form method="post" action="/photos138/result-review"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="result_id" value="{esc(row['result_id'])}"><div class="inline"><select name="review_status"><option value="candidate">candidate</option><option value="reviewed">reviewed</option><option value="linked">linked</option><option value="rejected">rejected</option></select><select name="result_kind"><option value="unknown">unknown</option><option value="exact_copy">exact_copy</option><option value="cropped_variant">cropped_variant</option><option value="edited_variant">edited_variant</option><option value="visually_similar">visually_similar</option><option value="context_only">context_only</option></select><input name="notes" value="{esc(row.get('notes') or '')}" placeholder="Prüfnotiz"><button class="small ghost">Treffer prüfen</button></div></form></div>''')
    return base + f'''
<hr><div class="notice"><b>Fotorecherche · Build 138:</b> Zusätzlich zu Original und bereinigter Kopie entstehen kontrollierte Suchvarianten, Provider-Serien, dokumentierte Treffer, lokale Dateivergleiche und vollständige Provenienzketten. Biometrische Gesichtsidentifizierung, Gesichtsabgleich und automatische Personenzuordnung bleiben deaktiviert.</div>
<div class="metrics"><div class="metric"><div class="label">Suchvarianten</div><div class="value">{esc(data['variant_count'])}</div></div><div class="metric"><div class="label">Provider-Läufe</div><div class="value">{esc(data['run_count'])}</div></div><div class="metric"><div class="label">Dokumentierte Treffer</div><div class="value">{esc(data['result_count'])}</div></div><div class="metric"><div class="label">Bildcluster</div><div class="value">{esc(data['cluster_count'])}</div></div></div>
<div class="two-col"><div class="panel"><h2>Recherchevariante erzeugen</h2><form method="post" action="/photos138/variant"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Originalfoto</label><select name="asset_id" required>{photo_options}</select></div><div class="field"><label>Variantenmodus</label><select name="variant_mode"><option value="clean_full">Vollbild bereinigt</option><option value="center_square">Zentraler quadratischer Ausschnitt</option><option value="manual_crop">Manueller Ausschnitt</option><option value="grayscale">Graustufen</option><option value="contrast">Kontrastoptimiert</option><option value="detail_enhance">Detailbetont</option></select></div><div class="field"><label>Bezeichnung</label><input name="label" placeholder="z. B. Porträt-Ausschnitt"></div><div class="form-grid"><div class="field"><label>Links</label><input type="number" name="left" min="0" value="0"></div><div class="field"><label>Oben</label><input type="number" name="top" min="0" value="0"></div><div class="field"><label>Rechts</label><input type="number" name="right" min="0" value="0"></div><div class="field"><label>Unten</label><input type="number" name="bottom" min="0" value="0"></div><div class="field"><label>Max. Kante</label><input type="number" name="max_dimension" min="256" max="3000" value="1600"></div><div class="field"><label>JPEG-Qualität</label><input type="number" name="quality" min="60" max="95" value="88"></div></div><button>Suchvariante erzeugen</button></form></div>
<div class="panel"><h2>Provider-Serie vorbereiten</h2><form method="post" action="/photos138/sweep"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Recherchedatei</label><select name="source_ref" required>{source_options}</select></div><div class="field"><label>Anbieter</label><div class="inline"><label><input type="checkbox" name="provider_google_lens" value="1" checked> Google Lens</label><label><input type="checkbox" name="provider_bing_visual" value="1" checked> Bing</label><label><input type="checkbox" name="provider_tineye" value="1" checked> TinEye</label><label><input type="checkbox" name="provider_yandex_images" value="1"> Yandex</label></div></div><div class="field"><label>Zweck</label><textarea name="purpose" rows="3" required></textarea></div><div class="field"><label>Freigabephrase</label><input name="confirmation" placeholder="FOTORECHERCHE-SERIE FREIGEBEN" required></div><button>Provider-Serie vorbereiten</button></form><p class="footer">Jeder Anbieter wird separat im isolierten Fallbrowser geöffnet. Uploads erfolgen ausschließlich manuell.</p></div></div>
<div class="panel"><h2>Build-138-Fotorecherche-Läufe</h2>{''.join(run_cards) if run_cards else '<div class="empty">Noch keine Provider-Serie vorbereitet.</div>'}</div>
<div class="two-col"><div class="panel"><h2>Treffer dokumentieren</h2><form method="post" action="/photos138/result"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Recherche-Lauf</label><select name="run_ref" required>{run_options}</select></div><div class="field"><label>Fundseite</label><input name="page_url" placeholder="https://..." required></div><div class="field"><label>Direkte Bildadresse, optional</label><input name="image_url" placeholder="https://..."></div><div class="field"><label>Seitentitel</label><input name="page_title"></div><div class="field"><label>Trefferart</label><select name="result_kind"><option value="unknown">Ungeklärt</option><option value="exact_copy">Exakte Kopie</option><option value="cropped_variant">Beschnittene Variante</option><option value="edited_variant">Bearbeitete Variante</option><option value="visually_similar">Visuell ähnlich</option><option value="context_only">Nur Kontextfund</option></select></div><div class="field"><label>Lokal gesichertes Ergebnisbild, optional</label><select name="local_result_asset_id">{result_asset_options}</select></div><div class="field"><label>Notiz</label><textarea name="notes" rows="3"></textarea></div><button>Treffer in Evidence Graph übernehmen</button></form></div>
<div class="panel"><h2>Lokale Bildcluster</h2><p>Clustert ausschließlich Bilddateien anhand aHash/dHash. Die Cluster sagen nichts über die Identität abgebildeter Personen aus.</p><form method="post" action="/photos138/clusters"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="form-grid"><div class="field"><label>aHash-Schwelle</label><input type="number" name="ahash_threshold" min="0" max="20" value="8"></div><div class="field"><label>dHash-Schwelle</label><input type="number" name="dhash_threshold" min="0" max="24" value="10"></div></div><button>Cluster neu berechnen</button></form><p>Aktuell: <b>{esc(data['cluster_count'])}</b> Cluster.</p></div></div>
<div class="panel"><h2>Dokumentierte Fototreffer</h2>{''.join(result_cards) if result_cards else '<div class="empty">Noch keine Treffer dokumentiert.</div>'}</div>
'''
