from __future__ import annotations
from typing import Any, Callable


def render_quality141(ctx: Any, case_id: str, csrf: str, *, esc: Callable[[Any], str]) -> str:
    data = ctx.build141.dashboard(case_id)
    sources = ctx.db.all("SELECT source_id,title,source_type FROM evidence_sources_138 WHERE case_id=? ORDER BY title", (case_id,))
    targets = ctx.targets.list_targets(case_id)
    workflows = ctx.build137.list_workflows(case_id=case_id)
    source_options = ''.join(f'<option value="{esc(r["source_id"])}">{esc(r["title"])} · {esc(r["source_type"])}</option>' for r in sources)
    target_options = '<option value="">Gesamter Fall</option>' + ''.join(f'<option value="{esc(r["target_id"])}">{esc(r["name"])}</option>' for r in targets)
    workflow_options = ''.join(f'<option value="{esc(r["workflow_id"])}">{esc(r["objective_text"])} · {esc(r["task_count"])} Aufgaben</option>' for r in workflows)
    quality_rows = ''.join(
        f'<tr><td>{esc(r["title"])}</td><td>{esc(r["classification"])}</td><td>{esc(round(float(r["overall_score"])*100))}%</td><td>{esc(r["quality_band"])}</td><td>{esc(", ".join(r.get("weaknesses", [])[:2]))}</td></tr>'
        for r in data["source_qualities"]
    ) or '<tr><td colspan="5">Noch keine Quellenqualitätsbewertung.</td></tr>'
    changes = []
    for r in data["source_changes"]:
        review = '' if r["status"] != "open" else f'''<form method="post" action="/quality141/change-review"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="change_id" value="{esc(r['change_id'])}"><select name="status"><option value="acknowledged">zur Kenntnis</option><option value="resolved">gelöst</option><option value="dismissed">verworfen</option></select><button class="small">Speichern</button></form>'''
        changes.append(f'<tr><td>{esc(r["created_at"])}</td><td>{esc(r["title"])}</td><td>{esc(r["change_type"])}</td><td>{esc(r["severity"])}</td><td>{esc(len(r.get("affected_assertion_ids", [])))}</td><td>{review or esc(r["status"])}</td></tr>')
    risks = ''.join(f'<article class="intake-card"><div class="intake-head"><h3>{esc(r["title"])}</h3><span class="badge">{esc(r["severity"])}</span></div><p>{esc(r["summary"])}</p><p><b>Empfehlung:</b> {esc(r["recommended_action"])}</p></article>' for r in data["source_risks"]) or '<div class="empty">Keine offenen Quellenrisiken.</div>'
    analyses = ''.join(f'<tr><td>{esc(r["created_at"])}</td><td>{esc(r["objective"])}</td><td>{esc(round(float(r["evidence_quality_score"])*100))}%</td><td>{esc(r["uncertainty_band"])}</td><td>0</td></tr>' for r in data["analyses"]) or '<tr><td colspan="5">Noch keine Build-141-Analyse.</td></tr>'
    envelopes = ''.join(f'<tr><td>{esc(r["created_at"])}</td><td>{esc(r["destination_type"])}</td><td>{esc(r["risk_level"])}</td><td>{"blockiert" if r["blocked"] else esc(r["approval_status"])}</td><td>{esc(r["consumed_actions"])} / {esc(r["max_external_actions"])}</td></tr>' for r in data["envelopes"]) or '<tr><td colspan="5">Noch kein OPSEC-Ausführungsfenster.</td></tr>'
    opts = ''.join(f'<tr><td>{esc(r["created_at"])}</td><td>{esc(r["workflow_id"])}</td><td>{esc(r["estimated_minutes_saved"])}</td><td>{"ja" if r["applied"] else "Dry Run"}</td></tr>' for r in data["optimizations"]) or '<tr><td colspan="4">Noch keine Workflow-Optimierung.</td></tr>'
    m = data["metrics"]
    return f'''
<div class="notice"><b>Build 141 · Source Quality, Change Watch & Efficient Operations:</b> Quellenqualität, Abhängigkeit und Änderungen werden lokal nachvollzogen. AI-Aussagen werden bei veränderten Quellen neu gewichtet; OPSEC-Fenster sind zeitlich, inhaltlich und mengenmäßig begrenzt. Workflow-Optimierungen starten immer als Dry Run.</div>
<div class="metrics"><div class="metric"><div class="label">Bewertete Quellen</div><div class="value">{esc(m['source_count'])}</div></div><div class="metric"><div class="label">Offene Änderungen</div><div class="value">{esc(m['open_changes'])}</div></div><div class="metric"><div class="label">Offene Quellenrisiken</div><div class="value">{esc(m['open_risks'])}</div></div><div class="metric"><div class="label">Eingesparte Minuten</div><div class="value">{esc(m['estimated_minutes_saved'])}</div></div></div>
<div class="two-col"><div class="panel"><h2>Quellenqualität und Risiken prüfen</h2><form method="post" action="/quality141/case-scan"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><button>Alle Fallquellen bewerten und Risiken aktualisieren</button></form></div>
<div class="panel"><h2>Lokalen Quellen-Snapshot dokumentieren</h2><form method="post" action="/quality141/snapshot"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Quelle</label><select name="source_id" required>{source_options}</select></div><div class="field"><label>Beobachtete URL</label><input name="observed_url"></div><div class="field"><label>Titel</label><input name="observed_title"></div><div class="field"><label>HTTP-Status</label><input name="http_status" type="number" value="200"></div><div class="field"><label>Gesicherter sichtbarer Text/DOM-Auszug</label><textarea name="observed_text" rows="4" required></textarea></div><button>Snapshot hashen und vergleichen</button></form></div></div>
<div class="panel"><h2>Quellenqualitätsmatrix</h2><div class="table-wrap"><table><thead><tr><th>Quelle</th><th>Klasse</th><th>Score</th><th>Band</th><th>Prüfpunkte</th></tr></thead><tbody>{quality_rows}</tbody></table></div></div>
<div class="panel"><h2>Quellenänderungen</h2><div class="table-wrap"><table><thead><tr><th>Zeit</th><th>Quelle</th><th>Änderung</th><th>Schwere</th><th>Aussagen</th><th>Review</th></tr></thead><tbody>{''.join(changes) or '<tr><td colspan="6">Noch keine Änderung erkannt.</td></tr>'}</tbody></table></div></div>
<div class="panel"><h2>Quellen- und Evidenzrisiken</h2>{risks}</div>
<hr><div class="two-col"><div class="panel"><h2>Change-aware AI-Analyse</h2><form method="post" action="/quality141/analyze"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson optional</label><select name="target_id">{target_options}</select></div><div class="field"><label>Ermittlungsziel</label><textarea name="objective" rows="4" required></textarea></div><button>Belegqualität und Quellenänderungen einbeziehen</button></form></div>
<div class="panel"><h2>Begrenztes OPSEC-Ausführungsfenster</h2><form method="post" action="/quality141/envelope"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson optional</label><select name="target_id">{target_options}</select></div><div class="field"><label>Zweck</label><input name="purpose" required></div><div class="field"><label>Rechtsgrundlage</label><input name="legal_basis" value="berechtigtes Interesse" required></div><div class="field"><label>Zieltyp</label><select name="destination_type"><option value="guided_browser">Geführter Browser</option><option value="search_provider">Bild-/Suchanbieter</option><option value="external_ai">Externe AI</option><option value="human_reviewer">Menschlicher Prüfer</option><option value="local_only">Nur lokal</option></select></div><div class="field"><label>Zielbezeichnung</label><input name="destination_label"></div><div class="field"><label>Aktionstypen, kommagetrennt</label><input name="action_types" value="public_source_lookup"></div><div class="field"><label>Datenklassen, kommagetrennt</label><input name="data_classes" value="public_identifier"></div><div class="form-grid"><div class="field"><label>Max. Anker</label><input name="max_identity_anchors" type="number" min="0" max="3" value="1"></div><div class="field"><label>Max. externe Aktionen</label><input name="max_external_actions" type="number" min="0" max="4" value="1"></div><div class="field"><label>Gültigkeit Minuten</label><input name="ttl_minutes" type="number" min="5" max="120" value="30"></div></div><button>OPSEC-Fenster als Entwurf erstellen</button></form></div></div>
<div class="panel"><h2>Change-aware Analysen</h2><div class="table-wrap"><table><thead><tr><th>Zeit</th><th>Ziel</th><th>Qualität</th><th>Unsicherheit</th><th>Extern</th></tr></thead><tbody>{analyses}</tbody></table></div></div>
<div class="panel"><h2>OPSEC-Ausführungsfenster</h2><div class="table-wrap"><table><thead><tr><th>Zeit</th><th>Zieltyp</th><th>Risiko</th><th>Status</th><th>Budget</th></tr></thead><tbody>{envelopes}</tbody></table></div></div>
<hr><div class="two-col"><div class="panel"><h2>Workflow effizient ordnen</h2><form method="post" action="/quality141/optimize"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Workflow</label><select name="workflow_id" required>{workflow_options}</select></div><button>Dry Run: Dubletten, blockierte Quellen und nächste Schritte erkennen</button></form></div><div class="panel"><h2>Effizienzregeln</h2><ul><li>Exakte Suchdublette nur nach manueller Freigabe überspringen</li><li>Quarantänisierte oder geänderte Connectoren blockieren</li><li>Nächste Aktion nach Erkenntniswert, Status und Quellenlage priorisieren</li><li>Keine automatische Löschung von Aufgaben oder Belegen</li></ul></div></div>
<div class="panel"><h2>Optimierungsläufe</h2><div class="table-wrap"><table><thead><tr><th>Zeit</th><th>Workflow</th><th>Potenzial Minuten</th><th>Status</th></tr></thead><tbody>{opts}</tbody></table></div></div>
'''
