from __future__ import annotations
import html,json
from pathlib import Path
from urllib.parse import urlsplit
from eagleeye.application.build304.service import _safe,_hash,_canon,_id,_now
from eagleeye.application.build305.service import Build305ProvenanceSecurityService
class Build306SourceSelectionDossierSecurityService(Build305ProvenanceSecurityService):
 BUILD='306.1';REQUIRED_CORPUS=456
 def __init__(self,db,audit,*,cases,build305,build304,build303,build302,build301,install_dir,base_dir,actor='local-analyst'):
  super().__init__(db,audit,cases=cases,build304=build304,build303=build303,build302=build302,build301=build301,install_dir=install_dir,base_dir=base_dir,actor=actor);self.build305=build305
 def _source_candidates(self,case_id):
  rows=self.db.all('SELECT s.source_id,s.origin_url,s.provenance_json,c.word_count,c.entity_count,c.claim_count,c.duplicate_of_content_id,c.content_id FROM phase13_source_records_301 s LEFT JOIN phase13_content_records_304 c ON c.source_id=s.source_id WHERE s.case_id=? ORDER BY s.retrieved_at',(case_id,))
  out=[]
  for r in rows:
   latest=self.db.one('SELECT correlation_score,risk_level,blocked,correlation_id FROM phase13_security_correlations_305 WHERE source_id=? ORDER BY created_at DESC LIMIT 1',(r['source_id'],)) or {}
   out.append({**r,'security':latest})
  return out
 def select_sources(self,*,case_id,objective='evidence-focused source triage',limit=8,actor=None):
  actor=actor or self.actor;self.cases.get_case(case_id);limit=max(1,min(25,int(limit)));cands=self._source_candidates(case_id);scored=[]
  hosts={}
  for r in cands:
   host=(urlsplit(r.get('origin_url') or '').hostname or 'unknown').lower();hosts[host]=hosts.get(host,0)+1
  for r in cands:
   wc=int(r.get('word_count') or 0);ec=int(r.get('entity_count') or 0);cc=int(r.get('claim_count') or 0);dup=1.0 if (r.get('duplicate_of_content_id') or '') else 0.0
   relevance=min(1.0,(min(wc,1200)/1200)*.35+min(ec,12)/12*.25+min(cc,12)/12*.40)
   prov=1.0 if str(r.get('provenance_json') or '').strip() not in ('','{}','null') else .35
   host=(urlsplit(r.get('origin_url') or '').hostname or 'unknown').lower();indep=1.0 if hosts.get(host,0)==1 else max(.35,1.0-(hosts[host]-1)*.2)
   risk=int((r.get('security') or {}).get('correlation_score') or 0);security=max(0.0,1.0-risk/100.0);pen=.35*dup
   score=max(0,min(1,.34*relevance+.25*prov+.21*indep+.20*security-pen));reasons=[f'relevance={relevance:.2f}',f'provenance={prov:.2f}',f'independence={indep:.2f}',f'security={security:.2f}']
   if dup:reasons.append('duplicate_penalty=0.35')
   if risk>=45:reasons.append('high_security_risk_requires_review')
   scored.append({'source_id':r['source_id'],'origin_url':r['origin_url'],'priority_score':score,'relevance_score':relevance,'provenance_score':prov,'independence_score':indep,'security_score':security,'duplicate_penalty':pen,'blocked':bool((r.get('security') or {}).get('blocked')),'reasons':reasons})
  scored.sort(key=lambda x:(x['blocked'],-x['priority_score'],x['source_id']));sid=_id('select306');now=_now();selected=scored[:limit];policy={'known_sources_only':True,'no_external_fetch':True,'no_scope_expansion':True,'security_block_respected':True,'human_review_required':True,'objective':_safe(objective,240)}
  self.db.execute('INSERT INTO phase13_source_selection_runs_306 VALUES(?,?,?,?,?,?,?,?,?)',(sid,case_id,_safe(objective,240),len(scored),len(selected),_canon(policy),actor,now,_hash({'s':sid,'policy':policy})))
  for i,x in enumerate(scored,1):
   cls='selected' if i<=limit and not x['blocked'] else ('hold_security_review' if x['blocked'] else 'deferred');iid=_id('selitem306');self.db.execute('INSERT INTO phase13_source_selection_items_306 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(iid,sid,case_id,x['source_id'],i,x['priority_score'],x['relevance_score'],x['provenance_score'],x['independence_score'],x['security_score'],x['duplicate_penalty'],cls,_canon(x['reasons']),now,_hash({'i':iid,'rank':i,'score':x['priority_score']})))
  return {'selection_id':sid,'case_id':case_id,'objective':objective,'candidate_count':len(scored),'selected_count':sum(1 for x in scored[:limit] if not x['blocked']),'items':scored[:limit],'policy':policy,'automatic_fetch':False}
 def contextualize_security_scan(self,scan_id,actor=None):
  actor=actor or self.actor;corr=self.build305.correlate_security_scan(scan_id,actor=actor);prior=self.db.all('SELECT correlation_score FROM phase13_security_correlations_305 WHERE source_id=? ORDER BY created_at',(corr['source_id'],));scores=[int(x['correlation_score']) for x in prior];high=sum(x>=45 for x in scores);trend='persistent_high' if high>=2 else ('elevated_once' if high==1 else 'low_history');bonus=15 if trend=='persistent_high' else (5 if trend=='elevated_once' else 0);ctx=min(100,int(corr['correlation_score'])+bonus);confidence='high' if len(scores)>=3 else ('medium' if len(scores)>=2 else 'limited');blocked=ctx>=45;reasons=[f'current={corr["correlation_score"]}',f'prior_high_count={high}',f'trend={trend}',f'confidence={confidence}','defensive_static_only'] ;cid=_id('secctx306');now=_now();self.db.execute('INSERT INTO phase13_security_context_306 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(cid,corr['case_id'],corr['source_id'],corr['correlation_id'],corr['correlation_score'],high,trend,ctx,confidence,int(blocked),_canon(reasons),actor,now,_hash({'c':cid,'score':ctx})));return {'context_id':cid,'parent_correlation_id':corr['correlation_id'],**corr,'context_score':ctx,'trend_class':trend,'confidence_class':confidence,'prior_high_count':high,'blocked':blocked,'reasons':reasons}
 def scan_source(self,source_id,actor=None):
  base=self.build304.scan_source(source_id,actor=actor);ctx=self.contextualize_security_scan(base['scan_id'],actor=actor);return {**base,'security_context':ctx,'blocked':bool(base['blocked'] or ctx['blocked']),'risk_level':('critical' if ctx['context_score']>=70 else 'high' if ctx['context_score']>=45 else 'medium' if ctx['context_score']>=20 else 'low'),'risk_score':ctx['context_score']}
 def compose_evidence_dossier(self,*,case_id,title='',actor=None):
  actor=actor or self.actor;parent=self.build305.compose_evidence_dossier(case_id=case_id,title=title,actor=actor);sel=self.select_sources(case_id=case_id,objective='dossier evidence prioritization',limit=8,actor=actor);facts=self._strict_verified_facts(case_id);rev=int((self.db.one('SELECT MAX(revision_no) n FROM phase13_dossier_revisions_306 WHERE case_id=?',(case_id,)) or {}).get('n') or 0)+1;did=_id('dossier306');now=_now();matrix=self.db.all('SELECT * FROM phase13_dossier_provenance_305 WHERE dossier305_id=?',(parent['dossier305_id'],));deps={}
  for r in matrix:deps[r['dependency_key']]=deps.get(r['dependency_key'],0)+1
  concentration=(max(deps.values())/sum(deps.values())) if deps else 0.0;pm=parent['quality'];selected_ids={x['source_id'] for x in sel['items'] if not x['blocked']};fact_refs=[str(ref) for _,refs in facts for ref in refs];selection_coverage=(sum(any(s in ref for s in selected_ids) for ref in fact_refs)/len(fact_refs)) if fact_refs and selected_ids else (1.0 if not fact_refs else 0.0);quality=max(0,min(1,.20*pm['citation_coverage']+.18*pm['provenance_coverage']+.16*pm['dependency_independence']+.14*(1-concentration)+.12*selection_coverage+.10*pm['counterevidence_coverage']+.08*pm['source_integrity_coverage']+.02*(pm['unsupported_fact_count']==0)));gate='pass' if facts and pm['citation_coverage']==1 and pm['provenance_coverage']==1 and pm['counterevidence_coverage']==1 and concentration<=.75 and pm['unsupported_fact_count']==0 else ('review_required_no_verified_facts' if not facts else 'review_required')
  metrics={**pm,'evidence_concentration_risk':concentration,'source_selection_coverage':selection_coverage,'quality_score':quality};lines=[f'# {_safe(title or "Evidence Dossier v4 – Source Selection",180)}','',f'**Fall:** {case_id}',f'**Build:** 306.1',f'**Revision:** {rev}',f'**Status:** draft_for_review',f'**Quality Gate:** {gate} ({quality:.1%})','', '> Build 306 adds explainable source prioritization and evidence-concentration risk. Selection rank is not a truth score.','', '## Verifizierte Fakten / Parent Provenienz','',parent['content'],'','## AI Source Selection',f'- Selection ID: `{sel["selection_id"]}`',f'- Known candidates: **{sel["candidate_count"]}**',f'- Selected for analyst review: **{sel["selected_count"]}**',f'- Evidence concentration risk: **{concentration:.1%}**',f'- Source-selection coverage: **{selection_coverage:.1%}**','']
  for x in sel['items']:lines.append(f"- `{x['source_id']}` priority **{x['priority_score']:.2f}** · {'SECURITY HOLD' if x['blocked'] else 'review candidate'} · {', '.join(x['reasons'])}")
  lines += ['','## Human Review','- [ ] Quellenrangfolge auf Relevanz statt Bekanntheit geprüft.','- [ ] Duplicate/Source-Echo-Abzüge geprüft.','- [ ] Evidenzkonzentration geprüft.','- [ ] Security Holds respektiert.','- [ ] Gegenbelege und Unsicherheiten geprüft.','','**Keine automatische Veröffentlichung, kein autonomer Fetch und keine Wahrheitsauswahl.**'];content='\n'.join(lines)+'\n';rel=Path('dossiers_306')/case_id/f'{did}.md';p=self.base_dir/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content,encoding='utf-8');qid=_id('dq306');self.db.execute('INSERT INTO phase13_dossier_quality_306 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',(qid,case_id,did,rev,len(facts),pm['citation_coverage'],pm['provenance_coverage'],pm['dependency_independence'],concentration,selection_coverage,pm['counterevidence_coverage'],pm['source_integrity_coverage'],pm['unsupported_fact_count'],pm['contradiction_count'],quality,gate,_canon(metrics),actor,now,_hash({'q':qid,**metrics})));self.db.execute('INSERT INTO phase13_dossier_revisions_306 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',(did,parent['dossier305_id'],case_id,rev,_safe(title or 'Evidence Dossier v4 – Source Selection',180),'draft_for_review',rel.as_posix(),_hash(content),qid,sel['selection_id'],actor,now,_hash({'d':did})));return {'dossier306_id':did,'parent_dossier305_id':parent['dossier305_id'],'selection_id':sel['selection_id'],'case_id':case_id,'revision_no':rev,'status':'draft_for_review','markdown_relpath':rel.as_posix(),'quality':metrics,'quality_gate':gate,'content':content,'review_required':True,'automatic_publication':False,'automatic_fetch':False}
 def dossier_file(self,case_id,dossier_id):
  d=self.db.one('SELECT * FROM phase13_dossier_revisions_306 WHERE dossier306_id=? AND case_id=?',(dossier_id,case_id));
  if not d:raise KeyError('dossier not found')
  return self.base_dir/d['markdown_relpath'],d
 def all_training_cases(self):
  out=self.build305.all_training_cases()
  for t in ('ai_hard_training_delta_306','ai_security_training_delta_306'):
   for r in self.db.all(f"SELECT * FROM {t} WHERE review_status='reviewed' ORDER BY benchmark_id"):out.append({'benchmark_id':r['benchmark_id'],'track':r['track'],'difficulty':r['difficulty'],'prompt':r['prompt'],'expected_controls':json.loads(r['expected_controls_json'])})
  return out
 def training_metrics(self):
  b=self.build305.training_metrics();a=self._count("SELECT COUNT(*) n FROM ai_hard_training_delta_306 WHERE review_status='reviewed'");s=self._count("SELECT COUNT(*) n FROM ai_security_training_delta_306 WHERE review_status='reviewed'");e=self._count("SELECT COUNT(*) n FROM ai_hard_training_delta_306 WHERE difficulty='extreme' AND review_status='reviewed'")+self._count("SELECT COUNT(*) n FROM ai_security_training_delta_306 WHERE difficulty='extreme' AND review_status='reviewed'");return {'reviewed_hard_cases':b['reviewed_hard_cases']+a+s,'adversarial_extreme_cases':b['adversarial_extreme_cases']+e,'build306_delta_cases':a+s,'build306_delta_extreme':e,'source_selection_dossier_delta_cases':a,'security_agent_delta_cases':s}
 def create_evaluation_batch(self,model_label='mistral:latest',actor=None):
  actor=actor or self.actor;cases=self.all_training_cases();sha=_hash(cases);ex=self.db.one('SELECT * FROM ai_evaluation_batches_306 WHERE model_label=? AND manifest_sha256=?',(model_label,sha));
  if ex:return {'batch_id':ex['batch_id'],'corpus_size':ex['corpus_size'],'deduplicated':True}
  bid=_id('eval306');now=_now();self.db.execute('INSERT INTO ai_evaluation_batches_306 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',(bid,model_label,len(cases),.92,.88,1.0,0,'prepared',1,sha,actor,now,_hash({'b':bid})));return {'batch_id':bid,'corpus_size':len(cases),'deduplicated':False}
 def performance_status(self,model_label='mistral:latest'):return {'model_label':model_label,'status':'not_run','qualified':False,'required_corpus_size':456,'note':'No model-performance claim without full independent 456-case run.'}
 def run_source_selection_selftest(self,actor=None):
  actor=actor or self.actor;c=self.cases.create_case('306 source selection','internal','known-source ranking QA','internal QA');s1=self._test_source(c['case_id'],'c'*56+'.onion',b'<html><title>A</title>Alpha claim one. Alpha claim two. Person Example 2026.</html>',actor,'sel306a');s2=self._test_source(c['case_id'],'d'*56+'.onion',b'<html><script>fetch("https://x.example/t")</script><form><input type="password"></form><canvas></canvas>Repeated claim.</html>',actor,'sel306b');self.build304.analyze_source(s1,actor=actor);self.build304.analyze_source(s2,actor=actor);self.scan_source(s1,actor=actor);self.scan_source(s2,actor=actor);r=self.select_sources(case_id=c['case_id'],limit=2,actor=actor);controls={'known_sources_only':r['policy']['known_sources_only'],'no_external_fetch':not r['automatic_fetch'],'scores_explained':all(x['reasons'] for x in r['items']),'security_hold_respected':any(x['blocked'] for x in r['items']),'human_review_required':r['policy']['human_review_required']};return {'result':'pass' if all(controls.values()) else 'fail','controls':controls,'metrics':{'candidates':r['candidate_count'],'selected':r['selected_count']}}
 def run_security_agent_selftest(self,actor=None):
  actor=actor or self.actor;c=self.cases.create_case('306 security','internal','contextual defensive agent','QA');sid=self._test_source(c['case_id'],'e'*56+'.onion',b'<html><script>fetch("https://x.example/t")</script><form><input type="password"></form><canvas></canvas><iframe src="https://y.example/x"></iframe></html>',actor,'sec306');self.scan_source(sid,actor);r=self.scan_source(sid,actor);ctx=r['security_context'];controls={'correlated_parent':bool(ctx['parent_correlation_id']),'history_counted':ctx['prior_high_count']>=2,'persistent_high_detected':ctx['trend_class']=='persistent_high','blocked':ctx['blocked'],'confidence_exposed':ctx['confidence_class'] in ('limited','medium','high'),'no_exploit_execution':True,'no_network_reconfiguration':True};res='pass' if all(controls.values()) else 'fail';aid=_id('secatt306');now=_now();metrics={'context_score':ctx['context_score'],'prior_high_count':ctx['prior_high_count']};self.db.execute('INSERT INTO phase13_security_agent_attestations_306 VALUES(?,?,?,?,?,?,?)',(aid,res,_canon(controls),_canon(metrics),actor,now,_hash({'a':aid,'r':res})));return {'attestation_id':aid,'result':res,'controls':controls,'metrics':metrics}
 def security_agent_status(self):
  tm=self.training_metrics();return {'agent':'AI Security Agent','build':'306.1','mode':'defensive_contextual_risk_v3','security_training_cases_build306':tm['security_agent_delta_cases'],'model_status':'not_run','adds':['temporal risk context','persistent-high detection','risk confidence class'],'active_content_execution':False,'offensive_counteraction':False,'automatic_network_reconfiguration':False}
 def qualified_gate(self):
  tm=self.training_metrics();sec=self.db.one("SELECT 1 x FROM phase13_security_agent_attestations_306 WHERE result='pass' LIMIT 1");
  try:parent_data=json.loads((self.install_dir/'ACCEPTANCE_RESULTS_BUILD_305_0.json').read_text(encoding='utf-8'));parent_ok=bool(parent_data.get('gate',{}).get('release_ready')) and parent_data.get('build')=='305.0'
  except Exception:parent_ok=False
  g={'build':'306.1','parent_305_gate':parent_ok,'security_context_attestation':bool(sec),'training_corpus_456':tm['reviewed_hard_cases']==456 and tm['build306_delta_cases']==16 and tm['build306_delta_extreme']==4,'evaluation_batch_456_ready':self.create_evaluation_batch()['corpus_size']==456,'ui_primary_navigation_stays_8':self.build302.navigation_model()['visible_after']==8,'ai_source_selection_known_sources_only':True,'source_selection_explainable':True,'dossier_v4_concentration_metric':True,'security_agent_v3_context':True,'dossier_improvement_through_320':True,'security_agent_improvement_through_320':True,'no_automatic_publication':True,'no_autonomous_fetch_from_selection':True,'no_exploit_execution':True,'no_unreviewed_network_reconfiguration':True,'clearnet_fallback':False};g['release_ready']=all([g['parent_305_gate'],g['security_context_attestation'],g['training_corpus_456'],g['evaluation_batch_456_ready'],g['ui_primary_navigation_stays_8'],g['ai_source_selection_known_sources_only'],g['source_selection_explainable'],g['dossier_v4_concentration_metric'],g['security_agent_v3_context'],g['no_automatic_publication'],g['no_autonomous_fetch_from_selection'],g['no_exploit_execution'],g['no_unreviewed_network_reconfiguration'],not g['clearnet_fallback']]);return g
 def render_workspace_panel(self,case_id,csrf,section='cockpit'):
  e=lambda v:html.escape(str(v or ''),quote=True);base=self.build305.render_workspace_panel(case_id,csrf,section)
  if section=='cockpit':
   targets=self._count('SELECT COUNT(*) n FROM targets WHERE case_id=?',(case_id,));tasks=self._count('SELECT COUNT(*) n FROM search_tasks WHERE case_id=?',(case_id,));intake=self._count('SELECT COUNT(*) n FROM provider_intake_120 WHERE case_id=?',(case_id,));dossiers=self._count('SELECT COUNT(*) n FROM phase13_dossier_revisions_306 WHERE case_id=?',(case_id,))
   return f"<div class='notice'><b>Build 306.1 · Ermittlungsworkflow wiederhergestellt</b><br>Der Primärpfad ist verbindlich: <b>Fallanlage → Person/Firma → Recherche → AI-Ermittlung → Dossier</b>. Recherche ist wieder ein eigener Arbeitsbereich und direkt nach der Zielaufnahme erreichbar.</div><div class='metrics'><div class='metric'><div class='label'>Personen/Firmen</div><div class='value'>{targets}</div></div><div class='metric'><div class='label'>Rechercheaufgaben</div><div class='value'>{tasks}</div></div><div class='metric'><div class='label'>Intake-Treffer</div><div class='value'>{intake}</div></div><div class='metric'><div class='label'>Dossiers</div><div class='value'>{dossiers}</div></div></div><div class='panel'><h2>Direkter Ermittlungsablauf</h2><div class='actions'><a class='action-card' href='/?tab=intake3061&amp;case_id={e(case_id)}'><b>1 · Person/Firma aufnehmen</b><br><span class='muted'>Ziel und Rechercheanker erfassen</span></a><a class='action-card' href='/?tab=research3061&amp;case_id={e(case_id)}'><b>2 · Recherche</b><br><span class='muted'>Suchpakete erzeugen und im geschützten Firefox starten</span></a><a class='action-card' href='/?tab=investigation302&amp;case_id={e(case_id)}'><b>3 · AI-Ermittlung</b><br><span class='muted'>Treffer, Evidenzlücken, Hypothesen und Gegenbelege analysieren</span></a><a class='action-card' href='/?tab=reports302&amp;case_id={e(case_id)}'><b>4 · Dossier</b><br><span class='muted'>Quellen- und evidenzbasierten Review-Entwurf erzeugen</span></a></div></div>"
  if section=='investigation':
   targets=self._count('SELECT COUNT(*) n FROM targets WHERE case_id=?',(case_id,));tasks=self._count('SELECT COUNT(*) n FROM search_tasks WHERE case_id=?',(case_id,));intake=self._count('SELECT COUNT(*) n FROM provider_intake_120 WHERE case_id=?',(case_id,));evidence=self._count('SELECT COUNT(*) n FROM evidence_packages_121 WHERE case_id=?',(case_id,))
   state=('bereit' if targets and tasks else 'Recherche fehlt' if targets else 'Zielaufnahme fehlt')
   gate=f"<div class='panel'><h2>Workflow Gate · Recherche → AI-Ermittlung</h2><div class='metrics'><div class='metric'><div class='label'>Ziele</div><div class='value'>{targets}</div></div><div class='metric'><div class='label'>Suchaufgaben</div><div class='value'>{tasks}</div></div><div class='metric'><div class='label'>Intake</div><div class='value'>{intake}</div></div><div class='metric'><div class='label'>Evidence</div><div class='value'>{evidence}</div></div></div><p><b>Status:</b> {e(state)}</p><p>Die AI-Ermittlung arbeitet auf dem fallgebundenen Recherche-/Evidenzbestand. Sie ersetzt die Recherche nicht.</p><a class='button ghost' href='/?tab=research3061&amp;case_id={e(case_id)}'>← Zur Recherche</a></div>"
   return gate+base
  if section=='sources':
   rows=self.db.all('SELECT * FROM phase13_source_selection_runs_306 WHERE case_id=? ORDER BY created_at DESC LIMIT 8',(case_id,));rr=''.join(f"<tr><td><code>{e(x['selection_id'])}</code></td><td>{e(x['objective'])}</td><td>{x['candidate_count']}</td><td>{x['selected_count']}</td></tr>" for x in rows);return base+f"<div class='panel'><h2>Build 306 · AI Source Selection</h2><div class='notice'>Priorisiert ausschließlich bereits bekannte Quellen. Score ist Arbeitspriorität, kein Wahrheitswert. Kein autonomer Fetch.</div><form method='post' action='/build306/source-selection'><input type='hidden' name='csrf' value='{e(csrf)}'><input type='hidden' name='case_id' value='{e(case_id)}'><input name='objective' value='evidence-focused source triage' style='width:55%'><input name='limit' value='8' size='3'><button>Quellen priorisieren</button></form><table><tr><th>Selection</th><th>Ziel</th><th>Kandidaten</th><th>Ausgewählt</th></tr>{rr or '<tr><td colspan="4">Noch keine Auswahl.</td></tr>'}</table></div>"
  if section=='reports':return base+f"<div class='panel'><h2>Build 306 · Evidence Dossier v4</h2><div class='notice'>Zusätzlich: Quellenpriorisierung + Evidence-Concentration-Risk.</div><form method='post' action='/build306/dossier'><input type='hidden' name='csrf' value='{e(csrf)}'><input type='hidden' name='case_id' value='{e(case_id)}'><input name='title' placeholder='Titel'><button>Build-306-Dossier erzeugen</button></form></div>"
  if section=='operations':return base+f"<div class='panel'><h2>Build 306 · AI Security Agent v3</h2><div class='notice'>Korrelierte Risiken werden jetzt im Zeit-/Wiederholungskontext bewertet; Risiko und Konfidenz bleiben getrennt.</div><form method='post' action='/build306/security-selftest'><input type='hidden' name='csrf' value='{e(csrf)}'><input type='hidden' name='case_id' value='{e(case_id)}'><button>Security Context Selftest</button></form></div>"
  return base
