from __future__ import annotations

from typing import Any, Callable

from eagleeye.application.build138.service import EPISTEMIC_STATES, NODE_TYPES, REVIEW_STATES, SOURCE_TYPES, STANCES


def render_evidence138(ctx: Any, case_id: str, csrf: str, *, esc: Callable[[Any], str], table: Callable[..., str]) -> str:
    data = ctx.build138.evidence_dashboard(case_id)
    targets = ctx.db.all("SELECT target_id,name FROM targets WHERE case_id=? ORDER BY name", (case_id,))
    target_options = '<option value="">Fallweit / keine direkte Zielperson</option>' + ''.join(f'<option value="{esc(row["target_id"])}">{esc(row["name"])}</option>' for row in targets)
    node_options = ''.join(f'<option value="{esc(row["node_id"])}">{esc(row["node_type"])} · {esc(row["label"])}</option>' for row in data["nodes"]) or '<option value="">Zuerst Nodes synchronisieren oder anlegen</option>'
    source_options = ''.join(f'<option value="{esc(row["source_id"])}">{esc(row["source_type"])} · {esc(row["title"])}</option>' for row in data["sources"]) or '<option value="">Zuerst Quelle registrieren</option>'
    assertion_options = ''.join(f'<option value="{esc(row["assertion_id"])}">{esc(row["subject_label"])} — {esc(row["predicate"])} → {esc(row["object_label"])}</option>' for row in data["assertions"]) or '<option value="">Zuerst Aussage anlegen</option>'
    warning_cards = []
    for row in data["warnings"]:
        current = str(row.get("status") or "open")
        options = "".join(
            f'<option value="{esc(state)}"{" selected" if state == current else ""}>{esc(state)}</option>'
            for state in ("open", "acknowledged", "resolved", "dismissed")
        )
        warning_cards.append(f'''<div class="panel"><h3>{esc(row.get("severity", ""))} · {esc(row.get("title", ""))}</h3><p>{esc(row.get("summary", ""))}</p><p class="footer">Typ: {esc(row.get("warning_type", ""))} · Status: {esc(current)}</p><form method="post" action="/evidence138/warning"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="warning_id" value="{esc(row.get("warning_id", ""))}"><select name="status">{options}</select> <button class="small ghost">Status speichern</button></form></div>''')
    warning_html = "".join(warning_cards) or '<div class="notice">Keine Belegketten-Warnungen vorhanden.</div>'
    node_types = ''.join(f'<option value="{esc(key)}">{esc(key)}</option>' for key in sorted(NODE_TYPES))
    source_types = ''.join(f'<option value="{esc(key)}">{esc(key)}</option>' for key in sorted(SOURCE_TYPES))
    epistemic = ''.join(f'<option value="{esc(key)}">{esc(key)}</option>' for key in ("lead", "hypothesis", "supported", "confirmed", "contradictory", "refuted"))
    review_states = ''.join(f'<option value="{esc(key)}">{esc(key)}</option>' for key in sorted(REVIEW_STATES))
    stances = ''.join(f'<option value="{esc(key)}">{esc(key)}</option>' for key in sorted(STANCES))
    return f'''
<div class="notice"><b>Evidence Graph · Build 138:</b> Personen, Organisationen, Orte, Dokumente, Webseiten und Fotos werden als fallgebundene Nodes geführt. Aussagen bleiben getrennt von ihren Quellen, Bewertungen und Ableitungsketten.</div>
<div class="metrics"><div class="metric"><div class="label">Evidence Nodes</div><div class="value">{esc(data['node_count'])}</div></div><div class="metric"><div class="label">Aussagen</div><div class="value">{esc(data['assertion_count'])}</div></div><div class="metric"><div class="label">Quellen</div><div class="value">{esc(data['source_count'])}</div></div><div class="metric"><div class="label">Offene Warnungen</div><div class="value">{esc(data['open_warning_count'])}</div></div></div>
<div class="two-col"><div class="panel"><h2>Graph synchronisieren</h2><p>Übernimmt Zielpersonen, lokale Fotos, Recherchekopien, Varianten, Suchläufe und Fototreffer in den Build-138-Evidence-Graph.</p><form method="post" action="/evidence138/sync"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><button>Fallgraph synchronisieren</button></form></div><div class="panel"><h2>Integritätsanalyse</h2><p>Prüft Quellenabhängigkeit, Kopierketten, zirkuläre Provenienz, zeitliche Konflikte und fehlende Primärbelege.</p><form method="post" action="/evidence138/analyze"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><button>Belegketten prüfen</button></form></div></div>
<div class="two-col"><div class="panel"><h2>Evidence Node anlegen</h2><form method="post" action="/evidence138/node"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Node-Typ</label><select name="node_type">{node_types}</select></div><div class="field"><label>Bezeichnung</label><input name="label" required></div><div class="field"><label>Normalisierter eindeutiger Wert</label><input name="normalized_value" placeholder="z. B. example.org oder account:abc"></div><div class="field"><label>Zielperson, optional</label><select name="target_id">{target_options}</select></div><div class="field"><label>Prüfstatus</label><select name="review_state">{review_states}</select></div><button>Node speichern</button></form></div>
<div class="panel"><h2>Quelle registrieren</h2><form method="post" action="/evidence138/source"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Titel</label><input name="title" required></div><div class="field"><label>URL, optional</label><input name="canonical_url" placeholder="https://..."></div><div class="field"><label>Quellentyp</label><select name="source_type">{source_types}</select></div><div class="field"><label>Unabhängigkeitsgruppe</label><input name="independence_group" placeholder="Originalpublisher oder Ursprungsquelle"></div><div class="form-grid"><div class="field"><label>Publisher</label><input name="publisher"></div><div class="field"><label>Reliability 0–1</label><input type="number" name="reliability" min="0" max="1" step="0.05" value="0.5"></div></div><button>Quelle registrieren</button></form></div></div>
<div class="panel"><h2>Belegte Aussage anlegen</h2><form method="post" action="/evidence138/assertion"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="form-grid"><div class="field"><label>Subjekt</label><select name="subject_node_id" required>{node_options}</select></div><div class="field"><label>Objekt</label><select name="object_node_id" required>{node_options}</select></div><div class="field"><label>Prädikat</label><input name="predicate" placeholder="works_for / mentioned_in / located_at" required></div><div class="field"><label>Epistemischer Status</label><select name="epistemic_state">{epistemic}</select></div><div class="field"><label>Konfidenz</label><input type="number" name="confidence" min="0" max="1" step="0.05" value="0.5"></div><div class="field"><label>Zielperson, optional</label><select name="target_id">{target_options}</select></div><div class="field"><label>Gültig von</label><input name="valid_from" placeholder="YYYY / YYYY-MM / YYYY-MM-DD"></div><div class="field"><label>Gültig bis</label><input name="valid_to" placeholder="YYYY / YYYY-MM / YYYY-MM-DD"></div></div><div class="field"><label>Aussagetext</label><textarea name="assertion_text" rows="3" required></textarea></div><button>Aussage anlegen</button></form></div>
<div class="two-col"><div class="panel"><h2>Quelle an Aussage hängen</h2><form method="post" action="/evidence138/attach"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Aussage</label><select name="assertion_id" required>{assertion_options}</select></div><div class="field"><label>Quelle</label><select name="source_id" required>{source_options}</select></div><div class="field"><label>Haltung</label><select name="stance">{stances}</select></div><div class="field"><label>Gewicht</label><input type="number" name="weight" min="0" max="1" step="0.05" value="1"></div><div class="field"><label>Auszug</label><textarea name="excerpt" rows="2"></textarea></div><div class="field"><label>Begründung</label><textarea name="rationale" rows="2"></textarea></div><button>Quelle verknüpfen</button></form></div>
<div class="panel"><h2>Aussage prüfen</h2><form method="post" action="/evidence138/review"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Aussage</label><select name="assertion_id" required>{assertion_options}</select></div><div class="field"><label>Neuer Status</label><select name="epistemic_state">{epistemic}</select></div><div class="field"><label>Konfidenz</label><input type="number" name="confidence" min="0" max="1" step="0.05" value="0.5"></div><div class="field"><label>Prüfnotiz</label><textarea name="review_note" rows="3" required></textarea></div><button>Prüfung speichern</button></form></div></div>
<div class="panel"><h2>Aussagen</h2>{table(data['assertions'], [('subject_label','Subjekt'),('predicate','Prädikat'),('object_label','Objekt'),('epistemic_state','Status'),('confidence','Konfidenz'),('source_count','Quellen'),('independence_count','Unabhängig')])}</div>
<div class="panel"><h2>Quellen</h2>{table(data['sources'], [('source_type','Typ'),('title','Titel'),('publisher','Publisher'),('canonical_url','URL'),('independence_group','Ursprungsgruppe'),('reliability','Reliability')])}</div>
<div class="panel"><h2>Belegketten-Warnungen</h2>{warning_html}</div>
<div class="panel"><h2>Provenienz</h2>{table(data['provenance'], [('from_object_type','Von Typ'),('from_object_id','Von ID'),('relation_type','Relation'),('to_object_type','Zu Typ'),('to_object_id','Zu ID'),('created_at','Zeit')])}</div>
'''
