from __future__ import annotations
from typing import Any, Callable


def render_reports142(ctx: Any, case_id: str, csrf: str, *, esc: Callable[[Any], str]) -> str:
    data = ctx.build142.dashboard(case_id)
    targets = ctx.targets.list_targets(case_id)
    source_reports = ctx.db.all("SELECT report_id,title,status,review_decision FROM report_drafts_131 WHERE case_id=? ORDER BY updated_at DESC", (case_id,))
    target_options = '<option value="">Gesamter Fall</option>' + ''.join(f'<option value="{esc(t["target_id"])}">{esc(t["name"])}</option>' for t in targets)
    source_options = '<option value="">Ohne Build-131-Arbeitsbericht</option>' + ''.join(f'<option value="{esc(r["report_id"])}">{esc(r["title"])} · {esc(r["status"])}</option>' for r in source_reports)
    type_options = ''.join(f'<option value="{key}">{esc(label)}</option>' for key, label in [
        ("executive_summary", "Executive Summary"), ("person_profile", "Personenprofil"), ("full_investigation", "Vollständiger Ermittlungsbericht"), ("chronology", "Chronologie"), ("contradiction_report", "Widerspruchsbericht"), ("source_register", "Quellenverzeichnis"), ("hypothesis_assessment", "Hypothesenbewertung"), ("handover", "Übergabebericht")
    ])
    reports = []
    for row in data["reports"]:
        actions = [f'<a class="button ghost small" href="/api/report142?case_id={esc(case_id)}&report_id={esc(row["report142_id"])}">JSON</a>']
        if row["status"] == "draft" and not row["stale"]:
            actions.append(f'''<form class="inline" method="post" action="/reports142/request-review"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="report_id" value="{esc(row['report142_id'])}"><button class="small">Review anfordern</button></form>''')
        if row["status"] == "review_ready":
            actions.append(f'''<form method="post" action="/reports142/review" class="decision"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="report_id" value="{esc(row['report142_id'])}"><select name="decision"><option value="approved">genehmigen</option><option value="needs_revision">Überarbeitung</option><option value="deferred">zurückstellen</option><option value="rejected">verwerfen</option></select><input name="reason" minlength="12" required placeholder="Substanzielle Reviewbegründung"><button>Review</button></form>''')
        if row["status"] == "reviewed" and row["review_decision"] == "approved" and not row["stale"]:
            actions.append(f'''<form method="post" action="/reports142/release"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="report_id" value="{esc(row['report142_id'])}"><input name="release_label" value="Freigegebene Fassung"><input name="confirmation" placeholder="BERICHT ZUR VERÖFFENTLICHUNG FREIGEBEN" required><button>Unveränderliche Releasefassung erzeugen</button></form>''')
        reports.append(f'''<article class="intake-card"><div class="intake-head"><h3>{esc(row['title'])}</h3><span class="badge">{esc(row['status'])}{' · veraltet' if row['stale'] else ''}</span></div><p>{esc(row['report_type'])} · Zielgruppe {esc(row['audience'])} · Redaktion {esc(row['redaction_profile'])}</p><p><b>Zitierabdeckung:</b> {esc(round(float(row['citation_coverage'])*100))}% · <b>gestützt:</b> {esc(row['supported_claims'])} · <b>widersprüchlich:</b> {esc(row['contested_claims'])} · <b>unaufgelöst:</b> {esc(row['unresolved_claims'])}</p><p><code>{esc(row['content_sha256'])}</code></p>{''.join(actions)}</article>''')
    releases = []
    for row in data["releases"]:
        links = ' '.join(f'<a class="button ghost small" href="/reports142/download?case_id={esc(case_id)}&release_id={esc(row["release_id"])}&file_role={role}">{role.upper()}</a>' for role in ("html", "pdf", "json", "manifest"))
        verify = f'''<form class="inline" method="post" action="/reports142/verify"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><input type="hidden" name="release_id" value="{esc(row['release_id'])}"><button class="small">Integrität prüfen</button></form>'''
        releases.append(f'''<tr><td>{esc(row['release_no'])}</td><td>{esc(row['release_label'])}</td><td>{esc(row['audience'])}</td><td><code>{esc(row['manifest_sha256'])}</code></td><td>{links}{verify}</td></tr>''')
    m = data["metrics"]
    return f'''
<div class="notice"><b>Build 142 · Professional Reports & Immutable Exports:</b> Berichte werden aus einem festen Fall- und Evidenzsnapshot erzeugt, zitier- und widerspruchsgeprüft, nach Zielgruppe redigiert, manuell reviewed und erst danach als unveränderliche HTML-/PDF-/JSON-Fassung mit Hashmanifest veröffentlicht.</div>
<div class="metrics"><div class="metric"><div class="label">Berichte</div><div class="value">{esc(m['reports'])}</div></div><div class="metric"><div class="label">Im Review</div><div class="value">{esc(m['review_ready'])}</div></div><div class="metric"><div class="label">Releases</div><div class="value">{esc(m['released'])}</div></div><div class="metric"><div class="label">Integritätsfehler</div><div class="value">{esc(m['integrity_failures'])}</div></div></div>
<div class="two-col"><div class="panel"><h2>Professionellen Bericht erzeugen</h2><form method="post" action="/reports142/create"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zielperson optional</label><select name="target_id">{target_options}</select></div><div class="field"><label>Build-131-Arbeitsbericht optional</label><select name="source_report131_id">{source_options}</select></div><div class="field"><label>Berichtstyp</label><select name="report_type">{type_options}</select></div><div class="field"><label>Titel</label><input name="title" placeholder="wird andernfalls automatisch erzeugt"></div><div class="form-grid"><div class="field"><label>Zielgruppe</label><select name="audience"><option value="internal">intern</option><option value="supervisor">Aufsicht</option><option value="legal_review">Rechtsprüfung</option><option value="client">Auftraggeber</option><option value="handover">Übergabe</option><option value="public">öffentlich</option></select></div><div class="field"><label>Redaktionsprofil</label><select name="redaction_profile"><option value="internal_full">intern vollständig</option><option value="external_redacted">extern redigiert</option><option value="handover_minimized">Übergabe minimiert</option><option value="public_summary">öffentliche Zusammenfassung</option></select></div></div><button>Berichtssnapshot erzeugen</button></form></div>
<div class="panel"><h2>Freigabeprinzipien</h2><ul><li>Belastbare Aussagen benötigen Quellenreferenzen.</li><li>Widersprüche und Hypothesen bleiben sichtbar getrennt.</li><li>Externe Fassungen benötigen Vier-Augen-Review.</li><li>Releasefassungen sind unveränderlich und werden bei Änderungen neu versioniert.</li><li>Kein autonomer Export, keine externe AI, kein automatischer Bildupload.</li></ul></div></div>
<div class="panel"><h2>Berichte</h2>{''.join(reports) or '<div class="empty">Noch kein Build-142-Bericht.</div>'}</div>
<div class="panel"><h2>Unveränderliche Releasefassungen</h2><div class="table-wrap"><table><thead><tr><th>Nr.</th><th>Bezeichnung</th><th>Zielgruppe</th><th>Manifest SHA-256</th><th>Dateien</th></tr></thead><tbody>{''.join(releases) or '<tr><td colspan="5">Noch keine Releasefassung.</td></tr>'}</tbody></table></div></div>
'''
