from __future__ import annotations

from typing import Any, Callable


def render_security143(ctx: Any, case_id: str, csrf: str, *, esc: Callable[[Any], str], table: Callable[..., str]) -> str:
    data = ctx.build143.dashboard(case_id)
    personas = data.get("personas", [])
    accounts = data.get("accounts", [])
    egress = data.get("egress_profiles", [])
    sessions = data.get("sessions", [])
    assignments = data.get("assignments", [])
    persona_options = "".join(f'<option value="{esc(row["persona_id"])}">{esc(row["label"])} · {esc(row["status"])}</option>' for row in personas)
    egress_options = "".join(f'<option value="{esc(row["egress_id"])}">{esc(row["label"])} · {esc(row["mode"])} · {esc(row["status"])}</option>' for row in egress)
    account_options = '<option value="">Kein Account / nur öffentliche Recherche</option>' + "".join(f'<option value="{esc(row["account_id"])}">{esc(row["persona_label"])} · {esc(row["platform"])} · {esc(row["account_label"])}</option>' for row in accounts)
    session_options = "".join(f'<option value="{esc(row["session_id"])}">{esc(row["persona_label"])} · {esc(row["status"])} · {esc(row["egress_mode"])}</option>' for row in sessions)
    assignment_options = "".join(f'<option value="{esc(row["assignment_id"])}">{esc(row["display_name"])} · {esc(row["role_key"])} · {"aktiv" if row["active"] else "inaktiv"}</option>' for row in assignments)
    metrics = data.get("metrics", {})
    return f'''
<div class="notice warn"><b>Build 143 · Controlled Collaboration, Research Personas & Egress Sessions:</b> Research-Personas dürfen ausschließlich synthetisch oder organisationsgebunden sein. EagleEye erstellt keine Drittanbieter-Konten, automatisiert keine Anmeldung und garantiert keine Anonymität oder Unverfolgbarkeit.</div>
<div class="metrics"><div class="metric"><div class="label">Personas / freigegeben</div><div class="value">{esc(metrics.get("personas",0))} / {esc(metrics.get("approved_personas",0))}</div></div><div class="metric"><div class="label">Alias-Konten</div><div class="value">{esc(metrics.get("accounts",0))}</div></div><div class="metric"><div class="label">Egress-Profile</div><div class="value">{esc(metrics.get("egress_profiles",0))}</div></div><div class="metric"><div class="label">Aktive Sitzungen</div><div class="value">{esc(metrics.get("active_sessions",0))}</div></div></div>
<div class="two-col"><div class="panel"><h2>Research-Persona anlegen</h2><form method="post" action="/security143/persona"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Interne Bezeichnung</label><input name="label" required></div><div class="field"><label>Typ</label><select name="persona_type"><option value="synthetic_alias">Synthetischer Alias</option><option value="organization_owned">Organisationskonto</option><option value="pseudonymous_research">Pseudonyme Recherchepersona</option></select></div><div class="field"><label>Zweck</label><textarea name="purpose" rows="3" required></textarea></div><div class="field"><label>Rechtsgrundlage / Mandat</label><textarea name="legal_basis" rows="3" required></textarea></div><div class="field"><label>Kontaktalias, optional</label><input name="contact_alias"></div><div class="field"><label>Risiko</label><select name="risk_level"><option>low</option><option selected>medium</option><option>high</option></select></div><div class="inline"><label><input type="checkbox" name="synthetic_identity_confirmed" value="1" required> synthetisch/organisationsgebunden</label><label><input type="checkbox" name="no_existing_person_impersonation" value="1" required> keine reale Person imitiert</label></div><p><button>Persona zur Prüfung anlegen</button></p></form></div>
<div class="panel"><h2>Persona prüfen</h2><form method="post" action="/security143/persona-review"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Persona</label><select name="persona_id" required>{persona_options}</select></div><div class="field"><label>Entscheidung</label><select name="decision"><option value="approved">Freigeben</option><option value="rejected">Ablehnen</option><option value="suspended">Sperren</option><option value="retired">Ausmustern</option></select></div><div class="field"><label>Begründung</label><textarea name="reason" rows="3" required></textarea></div><div class="field"><label>Freigabephrase</label><input name="confirmation" placeholder="RESEARCH-PERSONA FREIGEBEN"></div><p><button>Review speichern</button></p></form></div></div>
<div class="panel"><h2>Research-Personas</h2>{table(personas, [("label","Bezeichnung"),("persona_type","Typ"),("risk_level","Risiko"),("status","Status"),("requested_by","Antrag"),("approved_by","Review"),("expires_at","Ablauf")])}</div>
<div class="two-col"><div class="panel"><h2>Manuell angelegten Alias-Account registrieren</h2><p>Keine automatisierte Kontoerstellung. Geheimnisse werden verschlüsselt gespeichert und nicht in Berichte oder Audittexte übernommen.</p><form method="post" action="/security143/account"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Persona</label><select name="persona_id" required>{persona_options}</select></div><div class="field"><label>Plattform</label><input name="platform" required></div><div class="field"><label>Kontobezeichnung</label><input name="account_label" required></div><div class="field"><label>Benutzername-Alias</label><input name="username_alias"></div><div class="field"><label>E-Mail-Alias</label><input name="email_alias"></div><div class="field"><label>Herkunft</label><select name="account_origin"><option value="manual_existing">Manuell bestehend</option><option value="manual_authorized_creation">Manuell und autorisiert erstellt</option><option value="organization_provisioned">Durch Organisation provisioniert</option></select></div><div class="field"><label>Zugangsdaten, optional</label><input type="password" name="credential_secret" autocomplete="new-password"></div><div class="inline"><label><input type="checkbox" name="terms_reviewed" value="1"> Nutzungsbedingungen geprüft</label></div><div class="field"><label>Bestätigung</label><input name="confirmation" placeholder="KONTO MANUELL ANGELEGT UND BERECHTIGT" required></div><p><button>Account-Metadaten speichern</button></p></form></div>
<div class="panel"><h2>Egress-Profil anlegen</h2><p>Unterstützt manuell bereitgestellte HTTP-/SOCKS5-Proxies oder einen lokalen Tor-SOCKS-Endpunkt. EagleEye beschafft keine Proxykonten und verspricht keine Nicht-Zuordenbarkeit.</p><form method="post" action="/security143/egress"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Bezeichnung</label><input name="label" required></div><div class="field"><label>Modus</label><select name="mode"><option value="socks5">SOCKS5</option><option value="http_proxy">HTTP/HTTPS Proxy</option><option value="tor_local">Lokaler Tor-SOCKS</option><option value="direct">Direkt, nur für Tests</option><option value="system_proxy">Systemproxy, nicht für Herkunftstrennung</option></select></div><div class="form-grid"><div class="field"><label>Host</label><input name="proxy_host" placeholder="127.0.0.1"></div><div class="field"><label>Port</label><input type="number" name="proxy_port" value="9050"></div></div><div class="inline"><label><input type="checkbox" name="remote_dns" value="1" checked> Remote DNS</label><label><input type="checkbox" name="requires_auth" value="1"> Authentifizierung erforderlich</label></div><div class="field"><label>Proxy-Zugangsdaten, optional</label><input type="password" name="credential_secret"></div><div class="field"><label>Risikohinweis</label><textarea name="risk_note" rows="2"></textarea></div><p><button>Egress zur Prüfung anlegen</button></p></form></div></div>
<div class="two-col"><div class="panel"><h2>Egress prüfen</h2><form method="post" action="/security143/egress-review"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Egress</label><select name="egress_id" required>{egress_options}</select></div><div class="field"><label>Entscheidung</label><select name="decision"><option value="approved">Freigeben</option><option value="rejected">Ablehnen</option><option value="suspended">Sperren</option><option value="retired">Ausmustern</option></select></div><div class="field"><label>Begründung</label><textarea name="reason" rows="3" required></textarea></div><div class="field"><label>Freigabephrase</label><input name="confirmation" placeholder="EGRESS-PROFIL FREIGEBEN"></div><p><button>Review speichern</button></p></form></div><div class="panel"><h2>Alias-Konten</h2>{table(accounts, [("persona_label","Persona"),("platform","Plattform"),("account_label","Account"),("username_alias","Alias"),("terms_reviewed","Terms"),("secret_present","Secret"),("status","Status")])}</div></div>
<div class="panel"><h2>Egress-Profile</h2>{table(egress, [("label","Bezeichnung"),("mode","Modus"),("proxy_host","Host"),("proxy_port","Port"),("remote_dns","Remote DNS"),("status","Status"),("approved_by","Review")])}</div>
<div class="two-col"><div class="panel"><h2>Temporäre Research-Sitzung planen</h2><form method="post" action="/security143/session"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Persona</label><select name="persona_id" required>{persona_options}</select></div><div class="field"><label>Account, optional</label><select name="account_id">{account_options}</select></div><div class="field"><label>Egress</label><select name="egress_id" required>{egress_options}</select></div><div class="field"><label>Zweck</label><textarea name="purpose" rows="3" required></textarea></div><div class="field"><label>Rechtsgrundlage</label><textarea name="legal_basis" rows="3" required></textarea></div><div class="field"><label>Start-URL, optional</label><input name="start_url" placeholder="https://..."></div><div class="form-grid"><div class="field"><label>Aktionsbudget</label><input type="number" name="max_actions" value="20" min="1" max="100"></div><div class="field"><label>Dauer Minuten</label><input type="number" name="duration_minutes" value="60" min="10" max="240"></div></div><div class="inline"><label><input type="checkbox" name="require_origin_separation" value="1" checked> Herkunftstrennung erforderlich</label></div><p><button>Sitzung planen</button></p></form></div>
<div class="panel"><h2>Sitzung prüfen, freigeben und starten</h2><form method="post" action="/security143/session-request"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Sitzung</label><select name="session_id" required>{session_options}</select></div><p><button>OPSEC-Preflight und Reviewanfrage</button></p></form><hr><form method="post" action="/security143/session-approve"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Sitzung</label><select name="session_id" required>{session_options}</select></div><div class="field"><label>Begründung</label><textarea name="reason" rows="2" required></textarea></div><div class="field"><label>Freigabephrase</label><input name="confirmation" placeholder="RESEARCH-PERSONA-SITZUNG FREIGEBEN"></div><p><button>Vier-Augen-Freigabe</button></p></form><hr><form method="post" action="/security143/session-start"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Sitzung</label><select name="session_id" required>{session_options}</select></div><div class="field"><label>Startphrase</label><input name="confirmation" placeholder="RESEARCH-PERSONA-SITZUNG STARTEN"></div><p><button>Isolierten Sitzungsbrowser starten</button></p></form></div></div>
<div class="two-col"><div class="panel"><h2>Sitzungsschritt dokumentieren</h2><form method="post" action="/security143/session-action"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Sitzung</label><select name="session_id" required>{session_options}</select></div><div class="field"><label>Aktion</label><select name="action_type"><option>browse</option><option>search</option><option>manual_login</option><option>manual_upload</option><option>manual_download</option><option>note</option></select></div><div class="field"><label>Ziel-URL, optional</label><input name="destination_url"></div><p><button>Manuellen Schritt protokollieren</button></p></form></div><div class="panel"><h2>Sitzung schließen</h2><form method="post" action="/security143/session-close"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Sitzung</label><select name="session_id" required>{session_options}</select></div><div class="field"><label>Grund</label><textarea name="reason" rows="2" required></textarea></div><div class="field"><label>Bestätigung</label><input name="confirmation" placeholder="RESEARCH-SITZUNG BEENDET UND BROWSER GESCHLOSSEN"></div><p><button>Sitzung schließen und Profil löschen</button></p></form></div></div>
<div class="panel"><h2>Research-Sitzungen</h2>{table(sessions, [("persona_label","Persona"),("account_label","Account"),("egress_mode","Egress"),("status","Status"),("consumed_actions","Aktionen"),("max_actions","Budget"),("requested_by","Antrag"),("approved_by","Review"),("launched_at","Start")])}</div>
<div class="two-col"><div class="panel"><h2>Fallzugriffe prüfen</h2><form method="post" action="/security143/access-review"><input type="hidden" name="csrf" value="{esc(csrf)}"><input type="hidden" name="case_id" value="{esc(case_id)}"><div class="field"><label>Zuweisung</label><select name="assignment_id" required>{assignment_options}</select></div><div class="field"><label>Entscheidung</label><select name="decision"><option value="retain">Beibehalten</option><option value="needs_review">Erneut prüfen</option><option value="revoke">Widerrufen</option></select></div><div class="field"><label>Begründung</label><textarea name="reason" rows="3" required></textarea></div><div class="field"><label>Bestätigung</label><input name="confirmation" placeholder="FALLZUGRIFF MANUELL GEPRÜFT"></div><p><button>Zugriffsprüfung speichern</button></p></form></div><div class="panel"><h2>Aktive Rollen</h2>{table(assignments, [("display_name","Mitglied"),("role_key","Rolle"),("active","Aktiv"),("granted_by","Vergeben von"),("granted_at","Zeit")])}</div></div>
<div class="notice"><b>Grenzen:</b> Ein Proxy, VPN oder Tor kann die sichtbare Ausgangsadresse verändern, aber keine vollständige Nicht-Zuordenbarkeit garantieren. Plattformkonten, Browser- und Verhaltensfingerprints, Endpunktkompromittierung, Zahlungen, Cookies, Loginmuster und externe Protokolle können weiterhin Verknüpfungen ermöglichen.</div>
'''
